### ISSUE TITLE
Refreshing Remote Console Crashes OBS Studio

### ISSUE THREAD

**Issue by macharborguy** [obsproject/obs-browser#103]
Im not sure if this is a known issue or not, but ive noticed if i open the Remote Debugging Console in Chrome, reload the Browser Source directly in OBS, and then attempt to reload the Debug Console via the popup button (the one that says "Debugging Connection Was Closed.  Reason: WebSocket Disconnected", OBS crashes, but it does not mention the crash in the Log file.

If I reload the base level Debug Console (the one that shows the full list of Browser Sources), the crash does not happen.

I can reproduce this without fail every single time, and this happened on my previous OBS Streaming PC (old system was an i7 from 2009, current system is a newly built Ryzen 7 system)

**Comment by OsirisNL** [comment]
I can't reproduce this with recent versions of CEF, so i'm thinking it was just an issue in CEF itself.
