### ISSUE TITLE
Set --autoplay-policy in preparation for upcoming policy changes in Chrome

### ISSUE THREAD

**Issue by Lange** [obsproject/obs-browser#105]
Chromium's autoplay policy for videos is changing: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

This will affect every `obs-browser` source which imperatively plays `<video>` or `<audio>` elements, via things such as the `.play()` method on `HTMLMediaElement` instances.

Thankfully, there is a command line flag to disable this new policy:
```
--autoplay-policy=no-user-gesture-required
```

In preparation for newer versions of CEF, I recommend adding this flag to the default set of flags which `obs-browser` sets on its CEF instance ([shared/browser-app.cpp#L49-L65](https://github.com/kc5nra/obs-browser/blob/78d003b37abf53a7faf9ffdfed95fad84273d399/shared/browser-app.cpp#L49-L65)). I cannot think of many cases in which a user of `obs-browser` would want to have this new gestural requirement for media playback.

EDIT: This policy change is already present if CEF is built from source on `master`, which means we will definitely have to add this flag to `obs-browser` to prevent widespread breakages once `obs-browser` is using a new enough CEF to be affected.

**Comment by computerquip-streamlabs** [comment]
I've tried rebuilding the browser source with `command_line->AppendSwitchWithValue("autoplay-policy", "no-user-gesture-required");` added to the list of switches. This doesn't appear to work with libcef 3396 (chromium 67). I'm still unsure of the reason. Adding that switch to version 69.x of a chromium build works fine however. I can't seem to find an older build of chromium 67 to test.

**Comment by OsirisNL** [comment]
This flag is now set for every cef-bootstrap instance.

@computerquip-streamlabs It seems to work fine here with branch 3396

**Comment by computerquip-streamlabs** [comment]
Odd... I'll look over those builds I had then. I basically had the commit you had verbatim with no effect.

**Comment by computerquip-streamlabs** [comment]
Something must have been wrong with my build as it does work. Sorry about the false warning.

**Comment by RytoEX** [comment]
For reference, this was added in https://github.com/obsproject/obs-browser/commit/59958ebf8d3f223781e796beaf0849036b413938.

This issue can probably be closed, though the Web Audio API change coming in M70 may also require a change to be made.
