### ISSUE TITLE
Browser source briefly flickers incorrect image upon scene change

### ISSUE THREAD

**Issue by katarai** [obsproject/obs-browser#107]
See: https://obsproject.com/mantis/view.php?id=1182

Possibly related to this issue: https://github.com/kc5nra/obs-browser/issues/26

Briefly:

The browser source appears to hold the last frame of a webpage that is rendering animated elements via JavaScript or Flash (perhaps via other methods as well), then briefly re-output it as a still frame in a browser source in the scene being swapped to. Once the new browser source's page is loaded, it properly overwrites the still-frame.

This works consistently, as long as both scenes have browser sources, and at least one of those browser sources contains an element drawn via JavaScript or Flash.

This has been tested on multiple Windows systems across a number of different builds.

**Comment by OsirisNL** [comment]
This is expected behaviour since the browser source is still active even if you are in another scene. And it takes some time to tell CEF to refresh and for CEF to actually reload the page.

**Comment by katarai** [comment]
This occurs even if the browser sources have "shutdown when..." checked, which I assumed would deactivate the sources in the not-visible scene.

In addition, I'm very surprised to hear that having the _wrong_ page showing in a browser source is expected behavior. Is it not possible to prevent the browser sources in separate scenes from affecting each other?

To re-iterate, the browser sources in each scene are unique instances, pointing to different pages. If one of the sources happens to point to a page with JavaScript or Flash animated elements, then upon a scene change, that page is displayed in the _new_ browser source briefly. This includes taking on any of the position, filter, and so-on properties applied to the second source.

**Comment by OsirisNL** [comment]
"shutdown when..." completely shuts down the browser instance, so there is nothing there to render anything. 
I also cannot reproduce what you are talking about, i have 2 unique browser sources in 2 scenes, both with "shutdown when..." checked, both browser sources start blank whenever i switch to their respective scenes.

**Comment by katarai** [comment]
Please try it with the attached files, or with pages like this one: https://codepen.io/tarick/pen/jWOWOV

[stream.zip](https://github.com/kc5nra/obs-browser/files/1808508/stream.zip)


At least one of the sources has to be pointing to a page with an animating Javascript/HTML5 or Flash element. The result is as seen here: https://www.youtube.com/watch?v=rf5RuFCkdyY

**Comment by OsirisNL** [comment]
This is what it looks like for me: https://img.sokar.nl/img_1520972657_QWkkIpzggG0.mp4

**Comment by katarai** [comment]
Ah, sorry, forgot about the static files. Fixed that here.
[stream.zip](https://github.com/kc5nra/obs-browser/files/1808576/stream.zip)

Please test with a cut transition for clarity.

You can also test by swapping between the previous codepen.io page and this one: https://codepen.io/juliangarnier/pen/idhuG

This is what I see when using the codepen.io pages, with a hard-cut transition: https://www.youtube.com/watch?v=LWXIoewG3uY

**Comment by OsirisNL** [comment]
Both sources have "shutdown when..." checked and "refresh when..." unchecked?

**Comment by katarai** [comment]
Yup.
![generic](https://user-images.githubusercontent.com/17015918/37368891-beef8a38-26c4-11e8-8dfb-e917d0d7a711.png)

**Comment by katarai** [comment]
This problem appears to be resolved in the latest version bundled with OBS Studio 21.1. I'm not sure what the underlying cause of the issue was or what resolved it, but it seems quite gone.

As an aside, I'm wondering if it's possible to add a "Shutdown source when not active" option, to allow the fully shutdown behaviour in Studio Mode (it helps with those scoreboards).

I'd add it in myself, but it looks like I'd have to fully build both obs-studio and obs-browser from source to use it, so I'd prefer if it were added as an official feature.

--

Anyway, please feel free to close this, as I'm just leaving it open for a response before it's closed.

**Comment by OsirisNL** [comment]
I'm guessing this was resolved because of a CEF update.
