### ISSUE TITLE
getStatus is not presented under window.obsstudio.getStatus

### ISSUE THREAD

**Issue by kseptorl** [obsproject/obs-browser#111]
The method getStatus in undefined under window.obsstudio.

The window.obsstudio has only the next properties: [ 'pluginVersion', 'getCurrentScene' ]

OBS Browser source version: 1.30.1
OBS Verions: 21.0.3
OS: Mac

**Comment by OsirisNL** [comment]
The version included with 21.0.3 does not contain that feature.
