### ISSUE TITLE
getCurrentScene returns source name

### ISSUE THREAD

**Issue by BarryCarlyon** [obsproject/obs-browser#130]
> window.obsstudio.getCurrentScene(function(data) { console.log(data); });

Seems to return the name and dimensions of the source instead of the name of the scene that the source is present upon.

The `OBS_FRONTEND_EVENT_SCENE_CHANGED` event works correctly. But the function does not.

window.obsstudio.pluginVersion -> 2.1.1

**Comment by OsirisNL** [comment]
Fixed in 6390fade

**Comment by BarryCarlyon** [comment]
Ha. I was trying to trace the issue in the source when I saw you fixed it!
