### ISSUE TITLE
Double JSON in for obsSceneChanged

### ISSUE THREAD

**Issue by BarryCarlyon** [obsproject/obs-browser#131]
https://github.com/obsproject/obs-browser/blob/6390faded8be29c0f53910c635c3bb1209ed4bd8/browser-client.cpp#L127

Uses 

> args->SetString(1, json.dump());

Uses

https://github.com/obsproject/obs-browser/blob/d81d8dafe3eaa4298a17a2513aeb4e4174a08fe0/obs-browser-plugin.cpp#L358

> DispatchJSEvent("obsSceneChanged", json.dump().c_str());

As a result the example code:

> var t = document.createTextNode(evt.detail.name);

Does not function, but the following does

> var t = document.createTextNode(JSON.parse(evt.detail).name);

Bug? or Change?

**Comment by ChristopheCVB** [comment]
Certainly a bug, cost me some time to see that the problem doesn't come from my code :/
