### ISSUE TITLE
obsSceneChanged event return non parsed JSON

### ISSUE THREAD

**Issue by padinko** [obsproject/obs-browser#136]
Hello,
today i updated OBS from 21 to latest 22.0.2 and i noticed problem with event obsSceneChanged.
After some research I figured out that event.detail is a JSON string, not Object.

So now I need do this to get scene name:
```
window.addEventListener('obsSceneChanged', function(event) {
	const sceneName = JSON.parse(event.detail).name;
});
```

So you need maybe update this plugin or update documentation about this.

**Comment by OsirisNL** [comment]
Was already fixed in 06a5c12
