### ISSUE TITLE
[Request] Add proc handlers to source's public API for scripting

### ISSUE THREAD

**Issue by partlyhuman** [obsproject/obs-browser#140]
I would like to script a browser source, specifically I would love to call the source's Refresh() method from a Python OBS script. Adding proc handlers for the browser source's public methods (Refresh, SendMouse*, SendKey*) seems like it would be a simple way to accomplish this, if I understand correctly.

**Comment by alphasierra59** [comment]
I too have been looking for a way to refresh the browser through the python API.

**Comment by upgradeQ** [comment]
For Refresh() functionality you can update source settings like FPS or no-op CSS change and it will "refresh". See [this](https://obsproject.com/forum/resources/reset-browsers-sources.966/) script. 
For SendMouse, SendKey it's possible to use built-in obslua/obspython to route hotkey/mouse events into the browser source. 
Currently OBS has those [functions](https://obsproject.com/docs/search.html?q=obs_source_send) available:
- obs_source_send_focus 
- obs_source_send_key_click 
- obs_source_send_mouse_click 
- obs_source_send_mouse_move 
- obs_source_send_mouse_wheel 

Here is how to send a hotkey event to a browser source using [`obs-libre-macros`](https://github.com/upgradeQ/obs-libre-macros)  :
```lua
function send_hotkey_to_browser_source(source,hotkey_id_name)
  local key = obs.obs_key_from_name(hotkey_id_name)
  local vk = obs.obs_key_to_virtual_key(key)
  local event = obs.obs_key_event()
  event.native_vkey = vk
  event.native_modifiers = 0
  event.native_scancode = 0
  event.modifiers = 0
  event.text = ""
  obs.obs_source_send_key_click(source,event,false)
  obs.obs_source_send_key_click(source,event,true)
end
send_hotkey_to_browser_source(t.source,"OBS_KEY_Q")
```

**Comment by WizardCM** [comment]
Per @upgradeQ's comment, this is possible via standard OBS API functions, so I'm going to close this as it's a feature request that I would consider out of scope (not to mention I'd like to avoid feature requests in the Issues section).

**Comment by alphasierra59** [comment]
> 
> 
> Per @upgradeQ's comment, this is possible via standard OBS API functions, so I'm going to close this as it's a feature request that I would consider out of scope (not to mention I'd like to avoid feature requests in the Issues section).

Just to make sure I understand how that method works, it requires binding the refresh command to a hotkey, then calling that hotkey with the API?

**Comment by engineering222** [comment]
> For Refresh() functionality you can update source settings like FPS or no-op CSS change and it will "refresh". See [this](https://obsproject.com/forum/resources/reset-browsers-sources.966/) script. For SendMouse, SendKey it's possible to use built-in obslua/obspython to route hotkey/mouse events into the browser source. Currently OBS has those [functions](https://obsproject.com/docs/search.html?q=obs_source_send) available:
> 
> * obs_source_send_focus
> * obs_source_send_key_click
> * obs_source_send_mouse_click
> * obs_source_send_mouse_move
> * obs_source_send_mouse_wheel
> 
> Here is how to send a hotkey event to a browser source using [`obs-libre-macros`](https://github.com/upgradeQ/obs-libre-macros) :
> 
> ```lua
> function send_hotkey_tbs1(source,hotkey_id_name,key_up,key_modifiers)
>   local key = obs.obs_key_from_name(hotkey_id_name)
>   local vk = obs.obs_key_to_virtual_key(key)
>   local event = obs.obs_key_event()
>   event.native_vkey = vk
>   event.modifiers = get_modifiers(key_modifiers) -- bit or combination with interact keys
>   event.native_modifiers = event.modifiers
>   event.native_scancode = vk
>   event.text = "" -- it possible to leave it blank, keys are sent
>   obs.obs_source_send_key_click(source,event,key_up)
> end
> send_hotkey_tbs1(t.source,"OBS_KEY_Q",false)
> send_hotkey_tbs1(t.source,"OBS_KEY_Q",true)
> ```
> 
> Link to [`obs-browser`](https://github.com/obsproject/obs-browser/blob/51bf1e810f7433dbf4d4237ad3fc9aff8d841169/obs-browser-source.cpp#L306-L355) and to [Qt keys](https://doc.qt.io/qt-5/qkeyevent.html) . And example for mouse move
> 
> ```lua
> function send_mouse_move_tbs(source,x,y,key_modifiers)
>   local event = obs.obs_mouse_event()
>   event.modifiers = get_modifiers(key_modifiers)
>   event.x = x -- top left is [0,0] 
>   event.y = y
>   obs.obs_source_send_mouse_move(source,event,false) -- do not leave
> end
> ```
> 
> [EDIT] 2021.3.1 - Fix example & add links

I have no experience with coding and a little bit with streaming with OBS, can you tell me how I can set my web browser source Pomodoro timer to activate with a hotkey?
