### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by bazukas** [obsproject/obs-browser#141]
So I wanted to post this somewhere to have a discussion on what needs to be done to enable Linux support. Sorry if this is a wrong place for this.

Currently there are 2 big problems, but each have an easy (but ugly) workaround:

#### Need to include additional files, those are
- icudtl.dat
- natives_blob.bin
- snapshot_blob.bin
- v8_context_snapshot.bin
- cef.pak (documentation states that this is optional file, but cef crashed without it for me)

All those files have to be included in the same directory as `obs` and `obs-browser-page` (so in 2 places)
unfortunately that means that all those files have to be copied to /usr/bin in case of systemwide installation.
Also, need to include libcef.so in obs-plugins dir.

Interesting links on possible fix:
- https://bitbucket.org/chromiumembedded/cef/issues/1936/override-paths-dir_exe-dir_module-on-linux
- https://github.com/chromiumembedded/cef/pull/4

#### Glib conflict between qt5 and cef

For some reason CefRunMessageLoop() does not work. Replacing it with calling CefDoMessageLoopWork() in a loop works but quickly crashes (log: https://pastebin.com/4wnggfUQ).

Running obs with QT_NO_GLIB=1 fixes this behavior, browser source starts actually working.
My speculation is that since both qt and cef use glib in the same process they write to the same region in memory (??).
Edit: no need to replace CefRunMessageLoop if you set QT_NO_GLIB.

**Comment by kkartaltepe** [comment]
Glib shares the message loop between both CEF and QT by default. Neither provides an option to specify the glib context. This means that CEF is getting OBS messages and OBS is getting CEF messages (since both end up starting main loops against the same contexts). I believe the message loop code is buried in Chrome so there is next to no chance at getting that resolved without manually patching it. Its been a while since I investigated.

Allowing Qt to specify its glib context may be easier but also requires a patch.

Thanks so much for figuring out a workaround.

**Comment by bazukas** [comment]
Thanks for the explanation, @kkartaltepe 

I think one of the more straightforward ways to solve these problems would be to install obs binary together with cef files in a separate directory and place shell file in /usr/bin which would launch obs.
You can install obs-browser-page there as well in order to avoid duplicating files, alternatively use symlinks.

QT_NO_GLIB could be set in that shell file or using qputenv (if you decide to disable glib in obs).

**Comment by kkartaltepe** [comment]
The `QT_NO_GLIB` can be set any time before the QCoreApplication is `exec`'ed or the message loop is created. Simple test of setting it (with `setenv`)after https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L1649 (which is another QCoreApplication config line)

Some quick discussion with some Qt people seemingly knowledgeable this is really the only way to set it without compiling and distributing Qt ourselves and disabling glib.
