### ISSUE TITLE
Need way to get embedded scene name via JS

### ISSUE THREAD

**Issue by mphacker** [obsproject/obs-browser#145]
Scenario:  I have multiple scenes created.  One of them has an OBS browser source.   I can now take the scene that has the browser source and add it as a source to another scene.  In other words I have embedded the scene with the browser source inside of another scene.    My browser source is listening to the OBS scene change event.  Instead of getting the name of the scene it is in I am only getting back the root scene name.   In order for my browser source to display the correct layout I need to know what the name of the scene is where it is directly attached, not the root one.   Is this something that is doable?   I know a lot of streamers that have very complex scenes that have a lot of embedded scenes and having the full scene name hierarchy would be very useful.

**Comment by WizardCM** [comment]
This is a challenging request, as you're basically asking a sceneitem to know about itself, while trying to avoid information about the _source_ (a sceneitem is an instance of a source - a source is global).

I would personally vote that this shouldn't really be added, as it defeats the purpose of a source being consistent no matter where it is. You may be better off having unique browser sources in each scene/location.

**Comment by RytoEX** [comment]
Closing this as this is more of a feature request, and we use GitHub Issues for verified bug reports.  Per @WizardCM 's comment above, I think this is unlikely to be added as the distinction between sources and sceneitems makes it difficult to be reliable.
