### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by mphacker** [obsproject/obs-browser#147]
I setup the build for OBS Studio and was able to complete the latest build on Windows 10 (VS2017) without issue.  I then tried adding the flag to build the obs-browser plugin.   The build fails with an error on line 101 of browser-client.hpp:   'BrowserClient::GetViewRect': overriding virtual function return type differs and is not covariant from 'CefRenderHandler::GetViewRect'	

I also get another error for the same line that says: return type is not identical to nor covariant with return type "void" of overridden virtual function "CefRenderHandler::GetViewRect"	

Any ideas what might be wrong with my build setup?  The OBS-Studio build completes fine and I can run it.  It is just when I try to include obs-browser when things go sideways.

**Comment by WizardCM** [comment]
OBS Studio's master branch is designed for older versions of CEF, this includes the obs-browser submodule.

Before v23's release, this will be corrected. In the meantime, you will need to go into the submodule (the obs-browser subdirectory) and switch it to run on the master branch of obs-browser.

The error occurs only if you're using a newer version of CEF.

**Comment by mphacker** [comment]
Thanks @WizardCM !
