### ISSUE TITLE
OSX Hardware Acceleration

### ISSUE THREAD

**Issue by DDRBoxman** [obsproject/obs-browser#149]

**Comment by syropian** [comment]
Is there a link to the relevant PR/issue in CEF we could keep an eye on?

**Comment by WizardCM** [comment]
Thanks to the following PRs and the work of @PatTheMav and @pkviet - hardware acceleration is now available in OBS starting in [26.1.2](https://github.com/obsproject/obs-studio/releases/tag/26.1.2).

* #252
* https://github.com/obsproject/obs-studio/pull/3933
* https://github.com/obsproject/obs-studio/pull/3934
* https://github.com/obsproject/obs-studio/pull/4034

**Comment by syropian** [comment]
Amazing work! This seems to fix a long standing issue where videos in Browser Sources were really laggy. This is great news for anyone who utilizes webm video alerts!
