### ISSUE TITLE
Request: Changeable Default Audio Device

### ISSUE THREAD

**Issue by Alucard2112** [obsproject/obs-browser#15]
Hello,
I am using OBS Studio to stram to Twitch and am furthermore using your plugin to integrate twitchalerts into my stream. It would be very helpful to let me choose to witch audio output device the browser resource will broadcast as I am using multiple virtual audio cables to mix up my sound.
Thank you for your time.

**Comment by Gol-D-Ace** [comment]
AFAIK CEF doesn't support this.

**Comment by Alucard2112** [comment]
So there is no way to implement such a feature?^^

**Comment by Gol-D-Ace** [comment]
If CEF doesn't support it (I think @OsirisNL mentioned this before) then no.
The Browser Source is using CEF and so CEF would need to support it.

**Comment by Alucard2112** [comment]
Thanks for the information ;) that is rather unfortunate but now I know that I need to press them to implement the feature :D

**Comment by Gol-D-Ace** [comment]
Good luck with Google.

**Comment by OsirisNL** [comment]
Yeah, the CEF library has no way of handling the audio currently. It just sends it to the default audio device.

**Comment by Alucard2112** [comment]
Hey guys,
I have asked the developer on bitbucket to include such a feature whereas he referred to this forumpost:
http://magpcss.org/ceforum/viewtopic.php?f=7&t=10707
If I interpret the last answer correctly the option should be implemented since CEF3. Am I confusing something right now or is my interpretation correct?

**Comment by dodgepong** [comment]
I read that last post as asking a question without a question mark rather than making a statement of fact. Likely a case of poor grammar.

**Comment by OsirisNL** [comment]
Yeah that last statement is missing a question mark.

**Comment by Alucard2112** [comment]
Ah dang it!
I was hoping I was getting somewhere :D 
Thanks guys nonetheless :)

**Comment by kc5nra** [comment]
Chromium now has a audio device enum now enabled by flags for htnl5 audio.
Might be something that can be done if enabled as a parameter plus
JavaScript (if latest chromium used)

This all from memory, take with a grain of salt

On Monday, March 7, 2016, Alucard2112 <notifications@github.com> wrote:

> Ah dang it!
> I was hoping I was getting somewhere :D
> Thanks guys nonetheless :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kc5nra/obs-browser/issues/15#issuecomment-193281884>.
>


-- 
John R. Bradley
Turret Technology, LLC

(+1) 512-568-1665 (Voice)
(+1) 512-692-6198 (Fax)
jrb@turrettech.com

**Comment by galoko** [comment]
It can be done via hook a IMMDeviceEnumerator::GetDefaultAudioEndpoint method

**Comment by SReject** [comment]
Has there been progress made on resolving this. I'd like to be able to pipe the audio output into voice-meter(audio leveling software) to adjust volumes as needed

**Comment by OsirisNL** [comment]
Since Chromium doesn't have support for changing the output device, it's not possible.

**Comment by DDRBoxman** [comment]
Closing, refer to #11 for now
