### ISSUE TITLE
obsSceneChanged returned after transition ends

### ISSUE THREAD

**Issue by andrewtytula** [obsproject/obs-browser#161]
When listening for the "obsSceneChanged" event in the JavaScript bindings, it arrives after the transition animation is complete. The transition includes a "Transition Point" option to indicate how long after the transition animation starts that the scene should be switched, which OBS honors, other sources appear and disappear as expected.

Ex:
window.addEventListener("obsSceneChanged", function(evt) {console.log("scene changed"});

Expected Result:
Either a bug with OBS where it should be returning OBS_FRONTEND_EVENT_SCENE_CHANGED at the transition point, or we need to receive an event when the transition started with the transition point value (or even a transition point event) so the JavaScript code can wait and change scene at the expected time.

**Comment by WizardCM** [comment]
This is something I looked into when I was adding more events to the JS API (#150, #153) and as far as I can tell, there's no event for when a transition starts. There's probably a callback or something we could hook into instead, but I don't know the OBS APIs well enough to know where to look.

**Comment by andrewtytula** [comment]
I was originally going to file this under OBS but found some APIs that looked like they would work, but looking deeper it appears they won't. The other interesting thing I found was that even simple transitions like fade doesn't actually fade the browser source if they are in both scenes, which may kill what I want to do. I was looking at having one browser source that is used in all scenes but when the scene changes it would change the contents of the page too. Since it looks like it might not even be possible do to how transitions work with the same source in both, I will just close this for now and work around the problem.

**Comment by macharborguy** [comment]
OBS-WebSocket has an event that fires when a transition starts, but only if it is a transition other than a simple CUT.  Once the transition finishes, a SwitchScenes event is then fired.   If the transition is a CUT, only the SwitchScenes event is fired.

Relevant Code -> https://github.com/Palakis/obs-websocket/blob/43d38a2e636c343412ed5e998245198157ef459b/src/WSEvents.cpp#L725
