### ISSUE TITLE
CORS Same-origin XHR problems on Mac build

### ISSUE THREAD

**Issue by iameli** [obsproject/obs-browser#17]
I'm using obs-studio 0.13.1 and obs-browser 1.0.10 on OSX El Capitan.

I'm trying to stream the exact time using [time.is](http://time.is). When I try and do so, I get this image:

![screen shot 2016-03-20 at 3 33 34 pm](https://cloud.githubusercontent.com/assets/257909/13907692/248b655e-eeb1-11e5-8135-bf99b05ee528.png)

That "unable to connect with server" message appears to be the result of an XHR same-origin error -- I have the following in my OBS studio console:

```
[0320/153613:INFO:CONSOLE(0)] "XMLHttpRequest cannot load http://time.is/t/?en.0.60.-1.0p.-420.14e.1458513373002.1458513372246.. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://time.is' is therefore not allowed access.", source: http://time.is/ (0)
```

It seems to think it needs to enforce CORS headers when making that XHR, but the destination is exactly the same as the origin... pretty strange.

I don't have this problem when doing the exact same thing on any other browser on my mac, and I don't have this problem while using obs-browser on Windows.

Any ideas? Anything else I can do to diagnose this? Thanks!

**Comment by tmaneri** [comment]
We're running into this issue as well, and came to this exact conclusion. We had to force https and it seems to work, but that seems like a wonky work-around. Any info here would be appreciated.
