### ISSUE TITLE
Can record some wiondow as a video?

### ISSUE THREAD

**Issue by TheGreatGalaxy** [obsproject/obs-browser#175]
hi, I'm curious about this program can record some window which may be not the top window?
Now I want to find or develop a program to record a window as a vedio in linux/Ubuntu16.04. Anyone know about this? Thanks!

**Comment by WizardCM** [comment]
Your question is not related to the OBS Browser Source, and GitHub is not for questions. Try this page instead: https://obsproject.com/help
