### ISSUE TITLE
Browser source stopped supporting `.webm` video format

### ISSUE THREAD

**Issue by dkonopka** [obsproject/obs-browser#185]
## Expected Behavior
Browser source with `.webm` file should play as normal video.

## Current Behavior
Video freezes at beggining.

## Steps to Reproduce
1. Add some webpage with `.webm` file as Browser Source: e.g.: http://dl5.webmfiles.org/big-buck-bunny_trailer.webm
2. Video is not playing.

**Comment by Fenrirthviti** [comment]
Please provide a log. You have not specified what operating system or version you are using.

**Comment by derrod** [comment]
Please also specify what CEF build you're using (if you built obs-browser yourself).

**Comment by dkonopka** [comment]
I was able to reproduce this issue on the latest OBS version 24.0.3 (Windows) and 24.0.2 (Mac OSX), it is also possible to reproduce it in the latest Streamlabs OBS version.

**Comment by dodgepong** [comment]
I am able to add that exact link as a browser source and the video plays as expected in OBS Studio 24.0.3 for me. Please provide a log file.

**Comment by derrod** [comment]
With a minimal webpage that embeds the video it works perfectly fine:
```html
<html>
<body>
<video autoplay controls>
<source src="https://dl5.webmfiles.org/big-buck-bunny_trailer.webm" type="video/webm">
</video>
</body>
</html>
```

**Comment by dkonopka** [comment]
@dodgepong What do you mean by "log file"? I don't see any instruction to generate it in the issue template. 

What is interesting, I've downgraded to OBS 23.2.1 and it works perfectly, but still reproducing it on 24.0.3 version of OBS.

**Comment by btorellALTA** [comment]
In OBS go to Help > Log Files and upload the current or last log file, then link it here.

**Comment by dkonopka** [comment]
You can find more info about this issue here: https://github.com/obsproject/obs-studio/issues/2248

**Comment by WizardCM** [comment]
Closed in https://github.com/obsproject/obs-browser/pull/193
