### ISSUE TITLE
Mac OSX Build Instructions

### ISSUE THREAD

**Issue by nicholasc** [obsproject/obs-browser#19]
Hello,

I've been trying to compile plugin for OSX and since I'm not very familiar with cmake, I got stuck. I downloaded a stable CEF build and compiled the libcef_wrapper but when I try to compile obs-browser using `cmake . -DCEF_ROOT_DIR=/my/dir` and pass the build folder, I still get an error from FindCEF:

`CMake Error at FindCEF.cmake:21 (message):
  Could not find the CEF wrapper library
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)`

Any idea on why it can't locate it correctly? Anything would help really.

Thank you.

**Comment by sugarynugs** [comment]
set CEFWRAPPER_LIBRARY to the location of the libcef_wrapper.  CEF_ROOT_DIR is the top level directory.

**Comment by mzmiric5** [comment]
Has anyone had any luck with this? I got CEF compiled and the CEF_ROOT_DIR set, but obs-browser make (ran as part of obs-studio make) always gets stuck trying to link the CEF Helper app.

This is the output that I get
```
Linking CXX executable "CEF Helper.app/Contents/MacOS/CEF Helper"
Undefined symbols for architecture x86_64:
  "std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const", referenced from:
      std::string* cef::logging::MakeCheckOpString<CefWrapperType, CefWrapperType>(CefWrapperType const&, CefWrapperType const&, char const*) in libcef_dll_wrapper.a(libcef_dll_wrapper.cc.o)
      std::string* cef::logging::MakeCheckOpString<CefWrapperType, CefWrapperType>(CefWrapperType const&, CefWrapperType const&, char const*) in libcef_dll_wrapper.a(app_cpptoc.cc.o)
      .................
      std::string* cef::logging::MakeCheckOpString<CefWrapperType, CefWrapperType>(CefWrapperType const&, CefWrapperType const&, char const*) in libcef_dll_wrapper.a(completion_callback_cpptoc.cc.o)
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/obs-browser/CEF Helper.app/Contents/MacOS/CEF Helper] Error 1
make[1]: *** [plugins/obs-browser/CMakeFiles/cef-bootstrap.dir/all] Error 2
make: *** [all] Error 2
```
(full error at http://hastebin.com/yuxodaxinu.sh )

Seems to be similar to #9 but that doesn't seem to have had a resolution.

**Comment by miaulightouch** [comment]
@DDRBoxman, it's not working.

* browser-scheme.cpp:
 *  'obs.h' file not found

**Comment by DDRBoxman** [comment]
@miaulightouch it's going to do that until #29 or #31 get merged

**Comment by miaulightouch** [comment]
now the build is ok,
just remember copy **build/libcef_dll_wrapper/{BUILDTYPE}/libcef_dll_wrapper.a** to **build/libcef_dll** folder (create if not exist)

**Comment by vokama** [comment]
@miaulightouch it's not quite ok considering you need to find this comment section to solve the problem

**Comment by shadow0162** [comment]
Hi everyone,
Can you input texts in browser interact window on Mac version? why I can't type any word in browser view
