### ISSUE TITLE
macOS Build Issue

### ISSUE THREAD

**Issue by nguyer** [obsproject/obs-browser#208]
Hi there,

I'm trying to build on macOS Catalina. I've been following the steps outlined in the readme and I think I'm really close. However, when I run cmake, I'm getting the following:

```
CMake Error at plugins/CMakeLists.txt:82 (add_subdirectory):
  The binary directory

    /Users/nguyer/Code/obs-studio/build/plugins/obs-browser

  is already used to build a source directory.  It cannot be used to build
  source directory

    /Users/nguyer/Code/obs-studio/plugins/obs-browser

  Specify a unique binary directory name.
```

Does anyone know how to get past this? Any pointers are much appreciated! Thanks!

**Comment by Fenrirthviti** [comment]
The issues page is not for support. Please use the forums or Discord instead.
