### ISSUE TITLE
[BUG] Freezes system on streaming

### ISSUE THREAD

**Issue by AndrewDonelson** [obsproject/obs-browser#212]
Using the browser plugin to stream a page @ 1080P (any resolution really) causes the system to freeze after a while. Tracked the problem down using HTOP and noticed when I enabled the browser plugin in the scene, the CPU usage started at 86% (X2) and over a few minutes ticked up to 132% (X2) before freezing.

So I added a Window Capture to my scene for Firefox, disabled the browser plugin and started streaming again. Now the CPU usage is stable at 48%-50% (x2) with no increase over time and no system freeze.

## Platform
Operating system and version: Ubuntu 18.04 (Fully updated including nVidia driver)
OBS Studio version: Latest (25.x)

## Expected Behavior
1. System should not freeze / lockup entire computer
2. CPU Usage is to high and should not increase over time

## Current Behavior
CPU Usage should be approximately the same as Chrome, Firefox and not increase over time

## Steps to Reproduce

1. Use internal browser plugin to stream any URL
2. Note HTOP CPU Usage over a few minutes
3. Use Window Capture of Chrome or Firefox for Same URL
4. Note HTOP CPU Usage over a few minutes

## Additional information
No issues or lockups using Window Capture Plugin of External Firefox Browser. It is definitely something with the Internal Browser Plugin.

**Comment by WizardCM** [comment]
What method did you use to install OBS? Our official ppa?

**Comment by AndrewDonelson** [comment]
Wow, I'm sorry I don't remember. It's been installed for a while and updated several times. I do believe I used Ubuntu desktops software UI

**Comment by WizardCM** [comment]
Hmm, not sure about the easiest way to check.

Let's try this to determine if it's the snap package:
* Open OBS
* Go to File -> Show Settings Folder
* What is the full path to this settings folder?

Then let's check more info about the version:
`dpkg -l | grep obs-studio` should give us an exact version string and description (if `obs-studio` doesn't return anything, try just `obs`)

And finally, grab a log from OBS itself
* Help -> Log Files -> Upload Last Log File
* Paste the link below.

**Comment by AndrewDonelson** [comment]
Full Path to Settings folder: 
```
/home/andrew/.config/obs-studio
```
Version Info:
```
ii  obs-studio                                 25.0.3-0obsproject0~bionic                       amd64        OBS Studio for Ubuntu
```

Last Log:
```
https://obsproject.com/logs/DNNEqq_9yKxer-gZ
```

**Comment by WizardCM** [comment]
Final question from me for now (before I can test/validate myself), are you using the default nouveau Nvidia driver, or one of the proprietary Nvidia drivers available?

**Comment by AndrewDonelson** [comment]
Can you by any chance give me the command to look that up for you. I know I added a repo and I think my Nvidia driver version is 465. But what variant of the driver I'm not sure. I can tell you it's now been running for 17 hours using window capture instead of the browser with no lockups.

**Comment by Warchamp7** [comment]
I'm doing some tidying up on the repo, please re-open this if it is still an issue since I'm fairly sure we've updated CEF since this was originally posted and that could have solved it.
