### ISSUE TITLE
OBS Macbook Pro for OS X 10.10.5. download

### ISSUE THREAD

**Issue by jkDisko** [obsproject/obs-browser#220]
hi i've been trying to download OBS for macbook pro OS X 10.10.5.. I am not able to find this. I'd appreciate your help!!

**Comment by code-by-feets** [comment]
This isn't an issue with the code or program itself. Direct your question to the support website or the OBS Discord, not the Github repository.

**Comment by Fenrirthviti** [comment]
The issues pages are not for support. Please use the forums or discord.

https://obsproject.com/help
