### ISSUE TITLE
[BUG] Browser source missing from official Ubuntu packages

### ISSUE THREAD

**Issue by nekromoff** [obsproject/obs-browser#225]
## Platform

Operating system and version: Ubuntu 18.04
OBS Studio version: 25.0.8

## Expected Behavior
Browser source available

## Current Behavior
Browser source missing from official Ubuntu packages

## Steps to Reproduce
Install using official Ubuntu repo package, no browser source available after install

**Comment by nekromoff** [comment]
reported to incorrect repo, closing

**Comment by nekromoff** [comment]
I actually changed the bug title+description in the obs-studio, because the underlying issue is that the browser source is missing from the official Ubuntu repo/install of OBS-Studio

**Comment by Fenrirthviti** [comment]
https://github.com/obsproject/obs-browser/issues/219

Is why. Not really a bug, this is intentional until we can solve this issue.
