### ISSUE TITLE
What does this actually do?

### ISSUE THREAD

**Issue by winternet-studio** [obsproject/obs-browser#229]
Could the readme file at https://github.com/obsproject/obs-browser/blob/master/README.md please say what this plugin actually does? including what CEF means.

**Comment by skeletonbow** [comment]
This isn't the right place for support questions, this is for reporting software bugs.  Use the support channels in the Discord server or forums on the website for questions like this.

**Comment by winternet-studio** [comment]
Thought there was no reason for going through that whole loop for something as super simple and quickfix as adding a note to this repo.

**Comment by WizardCM** [comment]
Voila. https://github.com/obsproject/obs-browser/commit/2e5f316b5473f5e6c37a04c67000432001cac7f5

Thanks for the feedback! :)
