### ISSUE TITLE
browser Source on linux is missing on OBS 25.0.8-1

### ISSUE THREAD

**Issue by SJang1** [obsproject/obs-browser#230]
## Platform

Operating system and version: manjaro linux
OBS Studio version: 25.0.8-1

## Expected Behavior

`Starting with version 25, OBS Studio ships with browser source that work on Linux.` on `bazukas/obs-linuxbrowser` But it doesn't have browser source

## Current Behavior

![image](https://user-images.githubusercontent.com/29011440/85348157-b1da7680-b535-11ea-91a7-dd80b1b6f4b8.png)
No Browser Source

## Steps to Reproduce

1. update OBS Studio from Official Repo
2. open OBS, and See if it has browser source
3.
4.

**Comment by RytoEX** [comment]
This is a known issue.  See #219.

**Comment by kkartaltepe** [comment]
> update OBS Studio from Official Repo

There is no such repo for arch linux, for future reference. So you should open this bug against your package manager first.
