### ISSUE TITLE
Browser Source Compilation Fails on ARMv8 (Aarch64)

### ISSUE THREAD

**Issue by theofficialgman** [obsproject/obs-browser#234]
## Platform
Operating system and version: L4T Ubuntu 18.04
OBS Studio version:25.0.7
Hardware: Nintendo Switch (Tegra X1)
 
## Expected Behavior
Compilation succeeds and browser sources work.

## Current Behavior
When I go to compile OBS with browser source, the compilation fails since cef_atomicops_arm_gcc.h does not support armv8 yet. I follow these instructions to compile:

> wget https://cdn-fastly.obsproject.com/downloads/cef_binary_3770_linux64.tar.bz2
tar -xjf ./cef_binary_3770_linux64.tar.bz2
git clone --recursive https://github.com/obsproject/obs-studio.git
cd obs-studio
mkdir build && cd build
cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_3770_linux64" ..
make -j4
sudo make install

Compilation without the browser source works fine and OBS runs normally just without the browser source plugin.

Failure point:

> [ 66%] Building CXX object plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser-source.cpp.o
In file included from /home/garrett/cef_binary_3770_linux64/include/base/cef_atomicops.h:186:0,
                 from /home/garrett/cef_binary_3770_linux64/include/base/cef_atomic_ref_count.h:90,
                 from /home/garrett/cef_binary_3770_linux64/include/cef_base.h:34,
                 from /home/garrett/cef_binary_3770_linux64/include/cef_app.h:41,
                 from /home/garrett/obs-studio/plugins/obs-browser/cef-headers.hpp:30,
                 from /home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.hpp:24,
                 from /home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp:19:
/home/garrett/cef_binary_3770_linux64/include/base/internal/cef_atomicops_arm_gcc.h:287:2: error: #error "Your CPU's ARM architecture is not supported yet"
 #error "Your CPU's ARM architecture is not supported yet"
  ^~~~~
In file included from /home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp:20:0:
/home/garrett/obs-studio/plugins/obs-browser/browser-client.hpp: In constructor ‘BrowserClient::BrowserClient(BrowserSource*, bool, bool)’:
/home/garrett/obs-studio/plugins/obs-browser/browser-client.hpp:49:17: warning: ‘BrowserClient::bs’ will be initialized after [-Wreorder]
  BrowserSource *bs;
                 ^~
/home/garrett/obs-studio/plugins/obs-browser/browser-client.hpp:45:27: warning:   ‘bool BrowserClient::sharing_available’ [-Wreorder]
  bool sharing_available = false;
                           ^~~~~
/home/garrett/obs-studio/plugins/obs-browser/browser-client.hpp:53:9: warning:   when initialized here [-Wreorder]
  inline BrowserClient(BrowserSource *bs_, bool sharing_avail,
         ^~~~~~~~~~~~~
/home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp: In member function ‘void BrowserSource::SendKeyClick(const obs_key_event*, bool)’:
/home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp:299:11: warning: unused variable ‘modifiers’ [-Wunused-variable]
  uint32_t modifiers = event->modifiers;
           ^~~~~~~~~
plugins/obs-browser/CMakeFiles/obs-browser.dir/build.make:95: recipe for target 'plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser-source.cpp.o' failed
make[2]: *** [plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser-source.cpp.o] Error 1
CMakeFiles/Makefile2:1406: recipe for target 'plugins/obs-browser/CMakeFiles/obs-browser.dir/all' failed
make[1]: *** [plugins/obs-browser/CMakeFiles/obs-browser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 66%] Built target decklink-ouput-ui_autogen
CMakeFiles/Makefile2:1377: recipe for target 'plugins/obs-browser/CMakeFiles/obs-browser-page.dir/all' failed
make[1]: *** [plugins/obs-browser/CMakeFiles/obs-browser-page.dir/all] Error 2
[ 66%] Built target obs_autogen
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Fenrirthviti** [comment]
This error is coming from CEF. Our CEF binaries are compiled for x86/x64, you would need to recompile CEF on your own for ARM/64 support.

**Comment by theofficialgman** [comment]
@Fenrirthviti Alright, I'm struggling a bit to do what you said. Can I not download a binary from here (http://opensource.spotify.com/cefbuilds/index.html) for ARM64? Also, does it need to be the same CEF binary version (I noticed that the one in use if from mid 2019). Any help is greatly appreciated, I'm still new at all of this.

Note: Anything I build is being built on the target device so I shouldn't need to specify any target cpu.

**Comment by WizardCM** [comment]
@theofficialgman Looks like there are no 3770 ARM builds available from Spotify. You would need an ARM build of it for sure, and currently versions above 3770 are fairly incompatible with OBS. I'd suggest keeping an eye out for when we update to a new version (we're waiting on a couple PRs on the CEF side)

**Comment by theofficialgman** [comment]
@WizardCM yes i just figured that out. I managed to get the current version of CEF made for arm64 but run into this when I compile obs with browser support

> In file included from /home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp:20:0:
/home/garrett/obs-studio/plugins/obs-browser/browser-client.hpp:130:15: error: ‘virtual void BrowserClient::OnAudioStreamPacket(CefRefPtr<CefBrowser>, int, const float**, int, int64_t)’ marked ‘override’, but does not override
  virtual void OnAudioStreamPacket(CefRefPtr<CefBrowser> browser,

**Comment by WizardCM** [comment]
@theofficialgman yeah newer versions of CEF change the audio pipeline. [This diff](https://github.com/obsproject/obs-browser/compare/master...pkviet:audio3904) should help.

**Comment by theofficialgman** [comment]
@WizardCM thanks for pointing me to the diff, I've tried compiling from it but there isn't any documentation for compiling obs-browser from source on linux so I'm stumped.

**Comment by WizardCM** [comment]
@theofficialgman the CEF wrapper available to download from Spotify is just another cmake project, so be sure to build it first, then set `CEF_ROOT_DIR` in the OBS cmake project to the CEF wrapper root, cmake should do the rest.

**Comment by theofficialgman** [comment]
@WizardCM I did end up figuring out how to make the CEF binary from Spotify. My only trouble now is I don't know how to compile the obs-browser app from source on linux (previously I was just trying to install it with OBS studio when it is included precompiled).

**Comment by WizardCM** [comment]
@theofficialgman If you've 
* compiled the CEF wrapper that you downloaded from Spotify
* downloaded the obs-studio code with submodules
* configured OBS Studio with the `CEF_ROOT_DIR` cmake variable

then the rest should happen automatically when you build OBS using `make`.

`obs-browser` is just another plugin in OBS, and doesn't require anything extra.

**Comment by theofficialgman** [comment]
> @theofficialgman yeah newer versions of CEF change the audio pipeline. [This diff](https://github.com/obsproject/obs-browser/compare/master...pkviet:audio3904) should help.

@WizardCM But I can't use the default obs-browser plugin because of the audio pipeline incompatibilities. I need to download the obs-browser from the diff you mentioned earlier (which isn't precompiled) and swapping it out with the default obs-browser plugin just makes compiling obs report that obs-browser isn't included.

**Comment by WizardCM** [comment]
@theofficialgman That's not how swapping out code works. You will need to make the relevant code adjustments from above in your own obs-studio codebase and build OBS + obs-browser yourself. Due to a few changes, it will likely depend on that build of OBS too.

I'd personally recommend until we have our side updated with that code.

**Comment by theofficialgman** [comment]
@WizardCM I realize that and I am building OBS myself. My mistake earlier, I was having building issues because I accidentally deleted a CMakeLists.txt (no wonder none of the plugins were being built). Unfortunately even with the diff that you linked, replacing that instead of the default still leads to an error (though in a different part of the build).

> In file included from /home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp:20:0:
/home/garrett/obs-studio/plugins/obs-browser/browser-client.hpp:141:15: error: ‘virtual void BrowserClient::OnAudioStreamStarted(CefRefPtr<CefBrowser>, int, CefAudioHandler::ChannelLayout, int, int)’ marked ‘override’, but does not override
  virtual void OnAudioStreamStarted(CefRefPtr<CefBrowser> browser,
               ^~~~~~~~~~~~~~~~~~~~

and

> /home/garrett/obs-studio/plugins/obs-browser/obs-browser-source.cpp:117:53: error: invalid new-expression of abstract class type ‘BrowserClient’
    this, hwaccel && tex_sharing_avail, reroute_audio);
                                                     ^


I'm fine with waiting but just wanted to document
