### ISSUE TITLE
Browser Source crashes OBS in Big Sur

### ISSUE THREAD

**Issue by BaconWrappedShrimpWithEyes** [obsproject/obs-browser#235]
## Platform

Operating system and version: MacOS 11 Big Sur Public Beta 4
OBS Studio version: 25.0.8

## Expected Behavior

OBS should stream content that includes a browser source

## Current Behavior

When switching to a scene with a browser source, or adding a browser source, OBS stops responding. OBS does not freeze if the scene in Program has a browser source when the stream starts, only when adding a new browser source or switching to a scene containing a browser source.

I personally experienced freezes, other people seem to be reporting crashes.

## Steps to Reproduce

1. Have a MacOS 11 Big Sur beta installed
2. Open OBS
3. Add a browser source
4. Watch it hang

## Additional information

I didn't realize it at the time, but all my browser sources have custom CSS - specifically `body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }` (the default, mostly just to make the background transparent). Failed with combinations of Streamlabs Chat Box, Streamlabs Alert Box, and [Warp Bar](https://warp.world).

I didn't think to get an event log at the time. I've since downgraded back to Catalina, since I do rely on OBS, meaning I restored my laptop to a state pre-crashes. However, there are crash logs available in OBS Studio issues from other users [here](https://github.com/obsproject/obs-studio/issues/3095) and [here](https://github.com/obsproject/obs-studio/issues/3097). 

My hardware is very underpowered for OBS - I stream at 580p 15fps. 5500 bitrate, ultrafast encoder in order to keep a steady stream. However, others have also experienced the issue on better hardware, so this doesn't seem to be the issue.

I was surprised not to find this posted as an issue here already, and I wouldn't be surprised to hear that devs here are already aware of the issue, especially since /OBS-studio/ has already received several issues in this regard, and it's very clearly a Browser Source issue. However, I thought I'd bring the issue here where it belongs.

MacOS Big Sur will launch sometime in fall, probably October. Ideally, a fix would come before then.

Beta really does mean beta, so I couldn't tell you whether this was an OBS-browser issue or a MacOS bug. If someone tests and finds out it gets fixed by an OS update, I hope that gets posted here. I don't have the technical knowhow to figure out the issue's origin from the crash logs. OBS was not the only application to work fine on Catalina and not on Big Sur.

If I didn't downgrade, I would be testing against other CEF implementations to see if the issue was unique to OBS-browser or not. Unfortunately, to figure that out, others would need to do further testing.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Seems to work fine on Beta 5.

**Comment by WizardCM** [comment]
Thanks for verifying! Feel free to reopen if it occurs in a future build so that we can keep a close eye on things. :)

**Comment by thepatrick** [comment]
I'm hitting this, as soon as I add a browser source, OBS crashes.

Big Sur beta 5 (20A5354i) w/ OBS 25.0.8.

[obs_2020-08-30-152600_Zach.crash.txt](https://github.com/obsproject/obs-browser/files/5146386/obs_2020-08-30-152600_Zach.crash.txt)

**Comment by dodgepong** [comment]
Sounds like this issue is still present in the release. Going to re-open.

**Comment by elpop** [comment]
Crash happen on OBS 26.0.2 and Mac OS Big Sur 11.0.1 (release), I edit my .json scene and remove all the browse based sources and OBS can star and work as usual. The problem is when invoque a Browser-based source o try to add one.

**Comment by akapit** [comment]
There is any workaround so we can import streamlabs or any other similar service's assets without using this plugin until there is a fix?

**Comment by franckhlmartin** [comment]
It seems the same as https://github.com/obsproject/obs-studio/issues/3095  with a fix in https://github.com/obsproject/obs-browser/pull/256

**Comment by WizardCM** [comment]
Thanks to the following PRs and the work of @PatTheMav and @pkviet - hardware acceleration is now available in OBS starting in [26.1.2](https://github.com/obsproject/obs-studio/releases/tag/26.1.2). This also fixes the Big Sur crash by updating to a newer version of the browser backend.

* #252
* https://github.com/obsproject/obs-studio/pull/3933
* https://github.com/obsproject/obs-studio/pull/3934
* https://github.com/obsproject/obs-studio/pull/4034
