### ISSUE TITLE
Copy and Paste no longer supported in browser source

### ISSUE THREAD

**Issue by retaker** [obsproject/obs-browser#238]
## Platform

Operating system and version: Win10 2004
OBS Studio version: 25.0.8(64bit)

## Expected Behavior
When created a web browser source and click on "interact", I should be able to copy and paste information into the web browser source. 

## Current Behavior

I can not copy and paste into or out from the web browser source.

## Steps to Reproduce

1. create a web browser source, in the property, let the URL be "https://bing.com"
2. right-click on the source, click interact, try to copy and paste anything into the search box
3. you'll find there will be nothing goes into it.

## Additional information

I'm using ACT and WebSocket to show some data through web browser source, I have to copy and paste my setting into the window and the setting can only be copy and pasted since the web browser source does not support IME.
If not fix, basically the ACT and web socket is not usable for me.

**Comment by retaker** [comment]
not fixed in 26.0.2 hotfix

**Comment by WizardCM** [comment]
Fixed in #236 - this'll be available in the next major OBS version. Thanks for reporting!

**Comment by Rexios80** [comment]
This doesn't work on macos. Pasting on Windows works, but setting the clipboard contents in javascript does not.

**Comment by dustindmiller** [comment]
A year later and it still doesn't work on macOS.

**Comment by Rexios80** [comment]
Should probably make a new issue for it if that's the case

**Comment by gxalpha** [comment]
@dustindmiller Please open a new issue in that case. I believe that problem isn't directly related to this issue, but rather might be a result of the broken macOS hotkey system.

**Comment by dustindmiller** [comment]
@gxalpha Done.
