### ISSUE TITLE
Build breaks on aarch64: invalid conversion between vector type and integer type

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-browser#242]
I don't have log, someone else placed this BROKEN label into the FreeBSD port ```multimedia/obs-studio```.

**Comment by notr1ch** [comment]
This is not helpful without knowing the affected source file. Are you sure it involves obs-browser?

**Comment by yurivict** [comment]
The BROKEN_aarch64 has been there for 2+ years. I removed it and asked to post the log here in case it still breaks on aarch64.

**Comment by WizardCM** [comment]
Closing due to lack of context, information & reproduction steps.
