### ISSUE TITLE
[Browser] Symbols not typeable

### ISSUE THREAD

**Issue by cujomalainey** [obsproject/obs-browser#243]
## Platform
Operating system and version: OSX 10.15.6
OBS Studio version: OBS v25 and v26-rc3

## Expected Behavior
Type a key into browser interaction it will show up

## Current Behavior
Many symbols are not typeable when interacting with browser source

## Steps to Reproduce

1. Add browser source
2. Set url to google.com
3. Interact with browser
4. Try to type http:// in textbox

## Additional information
/\ appear to be fine but number row of symbols on US keyboard are all borked

**Comment by Scrxtchy** [comment]
Currently the macOS version lacks any support for key modifiers.
Work has been made to fix support for the Windows platform after it was broken in the Linux implementation, but someone with a mac should be able to dive into the keypress event modifiers and modify the `SendKeyClick` function to support them

https://github.com/obsproject/obs-browser/blob/master/obs-browser-source.cpp#L306

**Comment by WizardCM** [comment]
I've made progress in this area, but I want to revisit this tomorrow to see if I can get the final pieces working.

https://github.com/WizardCM/obs-browser/commit/54970a6c3ab051f18169b64defa4f6c72795c175

This fixes:
- All "text" characters - A-Z, 1-9, etc, etc
- Esc, Tab, Home/End/etc, NumPad, etc

This does not (yet) fix modifiers:
- Caps Lock
- Shift
- Ctrl
- Alt (Windows Key)
- Meta (Alt)
