### ISSUE TITLE
Variable collision in LocalStorage between different Custom Browser Docks

### ISSUE THREAD

**Issue by Novgorod** [obsproject/obs-browser#245]
## Platform

Operating system and version: Windows 10 x64
OBS Studio version: 26.0.2

## Expected Behavior

Data stored as variables in LocalStorage of the OBS browser should only be accessible (read/write) by the document (custom browser dock) that created them to avoid variable name collisions and security issues.

## Current Behavior

When a custom browser dock stores/persists data as variables in OBS browser's LocalStorage via the localStorage.setItem(id, value) javascript function, this data is not assigned to that particular custom browser dock in the LocalStorage levelDB database but instead is accessible by _all_ custom browser docks. Besides the obvious security issues, this leads to variable name collisions if two different docks happen to use the same generic variable names (like "theme") or if you want to duplicate a dock by renaming a copy of the html file, in which case all copied instances would use identical variable names in LocalStorage.

## Steps to Reproduce

1. Load at least two custom browser docks into OBS which use identical variable names for LocalStorage.
2. Let the first dock set variables in LocalStorage. This variables can be read by the second dock.
3. Let the second dock modify those variables in LocalStorage - the first dock can then re-read these changed variables.

You can reproduce it with any custom browser dock that uses LocalStorage and the simplest way is just to make a renamed duplicate because it will use the same variable names. See the attached zip file for a minimal example. It also contains a quick demo video: [LocalStorage.zip](https://github.com/obsproject/obs-studio/files/5370370/LocalStorage.zip)
The two html files in the zip archive are identical except for their file name. You can load both as custom browser docks and access the same LocalStorage data from either one. You can have as many renamed copies as you want and the LocalStorage data will be "shared" between them.

## Additional information

The issue is also described with more detail in [this forum post](https://obsproject.com/forum/threads/custom-browser-dock-variable-collision-in-localstorage-between-different-docks-bug.131768/). Possibly this issue was an oversight in the levelDB implementation because the raw levelDB data contains the prefix "_file://" before every variable name but it's not followed by an actual path to the custom browser dock's html file which would serve as a disambiguation. I also don't know if this issue only affects the custom browser dock or the entire OBS browser implementation (including the browser source).

**Comment by WizardCM** [comment]
This gets super tricky and I have mixed feelings.

Individual docks and browser sources don't have persistent unique identifiers of any kind (the user can change the name/url at any time).

For a real site, the localStorage context is limited to the current domain. This is consistent with standard browsers, and I see no reason to change this behaviour.

For local files, this is where it gets tricky. It's certainly possible to have multiple pages for a single dock (not everyone builds single-page apps, even in 2020). At the same time, you are correct - just because both docks are stored in a locally accesible location, doesn't mean they want to share everything.

In that case, maybe it makes sense to do it based on parent directory? But how do we expose that to the user/developer? To be honest, I don't even know if CEF ([docs](https://magpcss.org/ceforum/apidocs3/)) supports changing it like that. A quick Google tells me we'd likely have to create a new RequestContext.

**Comment by Novgorod** [comment]
Thanks for the prompt comment! You are right that technically a per-domain isolation is sufficient and the OBS browser implementation complies with that (i.e. if a dock is loaded from the web). On the other hand, the practical use case of custom browser docks as some kind of "local plugins" from different vendors calls for isolated environments, if only for security reasons.

The "proper" way with a separate RequestContext for each dock as you mentioned seems like a lot of work, so that decision is obviously up to the devs. However, I would say that 99.9% of all practical use cases of locally stored docks would be sufficiently covered by a simple per-document (i.e. file path) isolation and in the rare case when a multi-page dock happens to need to communicate LocalStorage data between pages, there are alternative methods (e.g. BroadcastChannels).

**Comment by PatTheMav** [comment]
Browser docks - for all intents and purposes - act like separate tabs of the same browser. Thus the same rules and limitations apply. While I understand the desire for such a feature, this would balloon the scope of browser docks beyond that which (afaik) actual browsers do and given our available resources I don't see us supporting this for the time being.

Also I fully expect there to be another group of people who _actively use_ this quirk right now and who'd want this to be a per-dock optional feature (increasing the feature's complexity even more).

**Comment by Warchamp7** [comment]
I'm doing some tidying up on the repo and given the above discussion closing this issue. If you are loading multiple docks from local files I'd suggest serving them from a domain to get the domain-specific isolation, or having enough control over them to be able to modify them and avoid data conflicts.
