### ISSUE TITLE
Browser not 'Secure' - Google Login

### ISSUE THREAD

**Issue by joegoldman** [obsproject/obs-browser#246]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 25.x / 26.x

## Expected Behavior

Interacting with a google login page should allow login to process

## Current Behavior

After entering username, get a warning stating Google can not sign in as the browser may not be secure/supported

## Steps to Reproduce

1. Add a browser to a Google resource
2. Interact with page
3. Try login to Google

## Additional information

I have researched this throughout google support and OBS - can not find a fix - some people suggest running as admin (no help for me), there's also a flag in your google account to allow less secure apps - I enabled this but still doesn't seem to help with OBS. I believe it is something in the way that the plugin is rendering that makes Google detect it as 'insecure'

**Comment by WizardCM** [comment]
This is entirely up to Google. We use CEF (Chromium Embedded Framework) to power the browser, and [last year they decided to block it](https://www.zdnet.com/article/google-bans-logins-from-embedded-browser-frameworks-to-prevent-mitm-phishing/).

In my experience, sometimes it works and sometimes it doesn't. We have no plans on faking a Chrome browser to bypass these restrictions.

**Comment by joegoldman** [comment]
I'm specifically trying to use hangouts to create multiple pre-defined rooms as a way to bring in webcams as a separate source (Rather than cutting up big meeting room style ones with crops) - can you think of any other way to get OBS to achieve login to hangouts or in your experience are you aware of another service that is similar I could use to pull in a users webcam remotely, and separately?

My current effort is to cut up window capture of discord but when more people join/leave and order changes etc it becomes very hard to manage the overhead.

**Comment by WizardCM** [comment]
http://obs.ninja seems to be a potentially good way these days.

**Comment by joegoldman** [comment]
Holy Crap. I love you. And I can self host it. I double love you - and the guy who wrote this.
