### ISSUE TITLE
obs-browser CSS problems: Cannot read property 'appendChild'

### ISSUE THREAD

**Issue by Pengi123** [obsproject/obs-browser#251]
I have problems with the obs-browser element.
When I add CSS code for some browsers I see in log weird error: obs-browser: Uncaught TypeError: Cannot read property 'appendChild' of null (source: www.example.com:1)

## Platform

Operating system and version: macOS Mojave 10.14.6
OBS Studio version: 26.0.2

## Expected Behavior

The obs-browser element needs to load instantly.

## Current Behavior

I see now that when I add CSS code that need 1-2 minutes to load CSS code for obs-browser

## Steps to Reproduce

In obs log i only see error code: obs-browser: Uncaught TypeError: Cannot read property 'appendChild' of null (source: www.example.com:1)

**Comment by Pengi123** [comment]
The "source" has <head> element.

**Comment by WizardCM** [comment]
Then the only reason it would delay adding the CSS is if the page hasn't finished loading. The code below runs `OnLoadEnd()`

https://github.com/obsproject/obs-browser/blob/7143a01e9499d0005129a1fbff844c8be5f16765/browser-client.cpp#L453-L459

**Comment by Pengi123** [comment]
Is possible to make it faster to instantly apply CSS code? before the page starts loading?

**Comment by WizardCM** [comment]
Not really, we wait for the page to finish loading so that we don't interrupt other code when we inject our own.

If you need custom CSS sooner, your best bet is modifying the page directly.

I'm closing this issue now as the behaviour is expected.
