### ISSUE TITLE
MacOS Browser-Source Memory Leak

### ISSUE THREAD

**Issue by r-i-c-h** [obsproject/obs-browser#257]
Don't see anything about this in the 26.1 patch notes...

## Platform
Operating system and version: MacOS 10.13.6
OBS Studio version: 26.0.2

## Expected Behavior
OBS Should not consume more than ___ (2gigs?) of RAM. 
 
## Current Behavior
Memory leak causes OBS to slowly consume more and more system RAM until OS throws errors and apps are forced to close.  When broadcasting [to twitch] while using the following as a Browser-Source layer in OBS (v26.0.2 / MacOS 10.13.6), the application slowly consumes more and more memory until hitting a system limit after ___mins (in my case ~30min) and a system dialogue pops up about forcing apps to close. On this layer I do have Shutdown-Source When Hidden + Refresh When scene becomes active both checked - As soon as I hide the display for this layer from the sources panel, memory consumption immediately drops down to "normal levels".  If I turn it back 'on', memory consumption begins to rise and the cycle repeats. 

## Steps to Reproduce
1. Add the following as a browser source:

```html
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>The Time</title>
</head>
<style>
  body {background: #4e4537; }
  #timebox {
    display: inline-block;
    font-size: 20px;
    font-family: 'Goldman', cursive;
    color: lightgray;
    border-radius: 5px;
    padding: 2px 5px;
    background-color: rgba(0, 0, 0, 0.5)
  }
 .pulse {animation: fadeinout 3s linear; }
  @keyframes fadeinout {    50% { opacity: 0; }  }
</style>
<body>
  <div id="timebox"></div>
  <script>
    const timeDiv = document.getElementById('timebox');
    function setTime() { // "Fri. Nov 20, 11:31PM"
      const currTime = new Date();
      const timeStr = currTime.toLocaleString('en-US', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric', seconds: 'numeric', hour12: true })
        .replace(' AM', 'am')
        .replace(' PM', 'pm')
        .replace(',', '.')
      timeDiv.innerHTML = timeStr.replace(':', `<span class="pulse">:</span>`);
      return null;
    }
    setInterval(() => { setTime() }, 3000); // yes, I'm only bothering every 3sec.
  </script>
</body>
</html>
```

2. Crop to a "smaller size" (don't think this has anything to do with it, but I *do* crop this layer, so...

3. Wait.

**Comment by WizardCM** [comment]
I cannot reproduce this issue on Windows. Additionally, I don't believe there's much we can do about bugs in the JS engine, which I expect this is part of.

**Comment by PatTheMav** [comment]
My JS is a bit rusty, but given that code I fully expect memory usage to balloon over time:

    setInterval(() => { setTime() }, 3000);

Every time the interval is triggered, a new closure is created, keeping references to `setTime` and associated globals (e.g. `timeDiv`). Mutations from inside intervals are evil to begin with, but in this case I'd expect this anonymous interval to gain a big number of retained closures over the time that are never cleaned up by GC (as the interval is not cleared).

    setInterval(setTime, 3000);

This would be the less "evil" version, because it doesn't need to retain a closure. But - again - my JS knowledge is very rusty these days.

**Comment by r-i-c-h** [comment]
@PatTheMav - I believe you are correct sir! I'll close this issue and give that a try. Thanks and sorry for registering spurious bug.
