### ISSUE TITLE
Facebook in the browser plugin. Playing a video doesn't work

### ISSUE THREAD

**Issue by fabianbur** [obsproject/obs-browser#258]
## Platform

Operating system and version: Linux Ubuntu 20.04
OBS Studio version: 26.1.0

## Expected Behavior

Open facebook in browser-plugin and play a video from there as a source.

## Current Behavior

Open facebook in browser-plugin and the video does not play.
## Steps to Reproduce

1.Open facebook in browser-plugin.
2.Play a live or recorded video
3.Does not play

## Additional information

07:43:26.797: obs-browser: ErrorUtils caught an error:
07:43:26.797: 
07:43:26.797: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.4d401e"') is unsupported.
07:43:26.797: 
07:43:26.797: Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs. (source: https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/UKxrrybl1hW.js?_nc_x=FCtl8d5fynP:59)

**Comment by WizardCM** [comment]
As we use Spotify CEF builds on Linux, they don't build with proprietary codecs. This is likely not something we will fix, unless there's a valid reason for us to build our own CEF on Linux (for example, if hardware acceleration becomes available).

**Comment by fabianbur** [comment]
Then it only remains to wait for someone to fix it. It would be a detail to have exactly the functionality of this wonderful piece of software than in Windows... But the fact that this entry closed is not a good sign.

Hardware acceleration in Linux is on, but it sure means something else.

**Comment by fabianbur** [comment]
I don't know how they fixed it, but Facebook Live and every other platform I've tried now works just like it does on Windows.
I'm glad that what was said didn't come true: "This is likely not something we will fix."

Thank you very much
