### ISSUE TITLE
[js interface] properties of the object returned by .getStatus() are non-descript.

### ISSUE THREAD

**Issue by SReject** [obsproject/obs-browser#268]
## Platform
Operating system and version: Windows 10
OBS Studio version: 26.1.1

## Expected Behavior
The properties returned by `obsstudio.getStatus()` should be either numbers or strings indicating the status of Streaming, Recording, Replaying, and VirtualCam

## Current Behavior
The current behavior is to return a boolean value indicating the overall status but such a value cannot account for the **four** possible states that streaming, recording and replaying can have: `starting`, `started`, `stopping`, `stopped`.

## Suggested Fix
Instead of returning a boolean value, return an unsigned integer which value equates to the following:
`0`: stopped
`1`: starting
`2`: started
`3`: stopping

**Comment by Warchamp7** [comment]
Closing as tthese bindings are not meant to be that granular in regards to output status.

As well, obs-websocket is now an official plugin and I believe _can_ offer that level of granularity.
