### ISSUE TITLE
[Feature request]  Browser Stinger Transition

### ISSUE THREAD

**Issue by w3suli** [obsproject/obs-browser#271]
Sorry to ask the question here and not on the OBS website.

I want to thank you for this great browser plugin.

I have been using OBS studio more seriously for half a year. And lately, the stinger transitions.

I was thinking about a browser stinger transition in the obs studio as well.

You can also create great animations in the browser. Web html-css animations would, in my opinion, also be suitable as a unique stinger transition.

Could this be solved?

**Comment by asher-the-thrasher** [comment]
Please use https://ideas.obsproject.com/ for any ideas or suggestions. This is meant for bugs or issues already implemented. Thank You!

**Comment by RytoEX** [comment]
GitHub Issues are for verified bug reports, not feature requests.  As you said, this can probably be done in a browser source with CSS animations, which are already supported.

**Comment by w3suli** [comment]
Current transitions:
-Fade to Black
-Cut
-Fade
-Stinger
-Luma Wipe

Stinger supported: mp4, ts, mov, wmv, flv, mkw, avi, gif, webm

Stinger not supported: html

Using the Browser plugin html-css animations could also be implemented as a transition between scenes I think.
