### ISSUE TITLE
> Emitting a signal on the dialog seems unnecessary. Does the transform dialog even need to know what scene the source is in? If it does need to know the scene, maybe listening for the scene change event within the dialog would be a better solution.

### ISSUE THREAD

**Issue by Britton1983** [obsproject/obs-browser#272]
> Emitting a signal on the dialog seems unnecessary. Does the transform dialog even need to know what scene the source is in? If it does need to know the scene, maybe listening for the scene change event within the dialog would be a better solution.

Thanks! I've updated the branch, feel free to take a look on it!

_Originally posted by @offthegrid-mike in https://github.com/obsproject/obs-studio/issues/4312#issuecomment-797234808_

**Comment by Fenrirthviti** [comment]
Sounds like you meant to reply somewhere, not open a new issue.
