### ISSUE TITLE
freezing the output

### ISSUE THREAD

**Issue by workingask** [obsproject/obs-browser#276]
1. add browser source to the scene 
2. insert any website url in it , (better if contains animation or image slider)
3. wait for 1-2 hour to see the animation inside this page that in the browser not moving until you refrash it manually or reopen OBS

**Comment by WizardCM** [comment]
Please fill in the full issue template, which includes providing a log file. Use the GitHub web UI and fill in the entire issue form.

**Comment by workingask** [comment]
I filled it allready two times , when submit , its empty
