### ISSUE TITLE
freezing the output

### ISSUE THREAD

**Issue by workingask** [obsproject/obs-browser#277]
Operating system and version: ubuntu 20.04
OBS Studio version: 26.1.2
OBS Log file: https://obsproject.com/logs/mHOCcs2-8mu5OhEO

## Expected Behavior
the browser should work all the time continuously .

## Current Behavior
the browser freezing the output after 1-2 hour from any manual refrash, and when I see the logs at that time , I see : 

> Failed to create xdg-screensaver: 2

the screen lock already disabled

## Steps to Reproduce
1. add browser source to the scene 
2. insert any website url in it , (better if contains animation or image slider)
3. wait for 1-2 hour to see the animation inside this page that in the browser not moving until you refrash it manually or reopen OBS

**Comment by RytoEX** [comment]
Is this the Snap version installed from Ubuntu Software?  Please try reproducing this with the version of obs-studio installed from our PPA.  We don't officially support the snap version, and I'm pretty sure they ask that bugs in that version should be reported to them.

https://snapcraft.io/install/obs-studio/ubuntu:
> This is a community-supported modified build of OBS Studio; please file issues on the Snapcrafters GitHub: https://github.com/snapcrafters/obs-studio/issues

**Comment by RytoEX** [comment]
Based on the module list, I'm fairly certain this is the Snap version of OBS Studio.  As such, and with no reply from the submitter confirming this issue appears in a supported version of OBS Studio, I'm going to close this.

If you can reproduce this in a supported version of OBS Studio, please comment and provide a reproducible test case with a specific website or HTML file to use for testing.
