### ISSUE TITLE
cef flag --disable-gpu added on linux

### ISSUE THREAD

**Issue by kkartaltepe** [obsproject/obs-browser#278]
Github ate my issue.

Expected:
CEF should use hardware rendering where possible

Actual:
https://github.com/obsproject/obs-browser/blame/master/browser-app.cpp#L79 is ancient code that disables cef's hardware rendering if the platform doesnt support texture sharing without explanation.

But if we force it with the `obs --enable-gpu` flag it works flawlessly. So im not sure why this section to disable it exists unless its related to functionality on other platforms. Id prefer not to shove some ifdef's here, so i made a bug.

**Comment by WizardCM** [comment]
What kinds of behaviours do you notice with/without the --disable-gpu flag?

**Comment by kkartaltepe** [comment]
The only difference I have found is that chrome with software rendering is slow and maxes out every core on my machine. Otherwise everything appears to function identically.

I tested, with webgl fish sample mostly, browser sources, docks, moving docks in and out, and browsing google search results for webgl fish test. Which worked with/without --disable-gpu on my machine.

**Comment by WizardCM** [comment]
As you're testing on linux, here's what my testing has confirmed:

```diff
bool enableGPU = command_line->HasSwitch("enable-gpu");
CefString type = command_line->GetSwitchValue("type");

if (!enableGPU && type.empty()) {
-   command_line->AppendSwitch("disable-gpu");
    command_line->AppendSwitch("disable-gpu-compositing");
}
```

**I'd be 100% comfortable with making this change.** Tested both sources & panels.

## Windows

### 4183, hwaccel disabled

✔ Enables rendering OpenGL
* Occasionally the 3D rendering aspect goes blank, but the rest of the page is fine.

❌ However, making this additional change breaks rendering entirely:
```diff
-   command_line->AppendSwitch("disable-gpu-compositing");
```

### 3770, hwaccel disabled

✔ Enables rendering OpenGL

### 3770, hwaccel enabled

✔ Does not cause any new issues

## macOS

### 4183, hwaccel disabled

✔ Enables rendering OpenGL

### 4183, hwaccel enabled

✔ Does not cause any new issues

**Comment by kkartaltepe** [comment]
Nice thats actually better performance to `disable-gpu-compositing` here. So the proposed changes look good to me.
