### ISSUE TITLE
Browser Source .html file's Javascript cannot see Custom CSS variables

### ISSUE THREAD

**Issue by wfolta** [obsproject/obs-browser#283]
### Operating System Info

macOS 10.15

### OBS Studio Version

27.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/pW6_h4RUQwfzCZdS

### Expected Behavior

Using a local .html file as the Browser Source and having set a variable in the Browser Source's Custom CSS preference, the standard Javascript for accessing a variable:

     <script>
      var db = getComputedStyle(document.body) ;
      document.getElementById('name').innerHTML =  db.getPropertyValue("--name").slice(2, -2)  ;
     </script>

should read the --name variable set in the Browser Source's Custom CSS area:

    body {
      --name: "My Name" ;
      --name-color: orange ;
    }

### Current Behavior

The Javascript does not see the variable. If the variable is set in the HTML file itself, the code works without modification. CSS values set in the Browser Source's Custom CSS do take effect, and using var(--name-color) for example in the CSS within the HTML file also works. It's appears to only be variables accessed via JavaScript that cause problems.

### Steps to Reproduce

1. Create a local HTML file that uses JavaScript in a <script> with getPropertyValue.
2. Set a variable in the Browser Source's Custom CSS.
3. Load the HTML file
4. You do not get the variable in your getPropertyValue

### Anything else we should know?

This is on a Mac. This is for a local HTML file, not a remote URI/URL. The usual CSS that you'd set in the Custom CSS works fine. It appears that even using var() in CSS in the HTML file works fine. It's just the JavaScript.

**Comment by RytoEX** [comment]
The browser source injects the custom CSS in its properties after the document has finished loading all resources.  See https://github.com/obsproject/obs-browser/blob/403b0ac6f1542ea5d590f8efebecf1a034c4a31b/browser-client.cpp#L453-L472

I'd guess that your JavaScript is running before obs-browser has injected the custom CSS.  Have you tried waiting until after an onReady or onLoad event?

**Comment by wfolta** [comment]
I had put the code into the DIVs in question, assuming that the JavaScript would be executed after all of the CSS was done and the DIV itself was set up. So I assume if this doesn't work then HTML onload won't work and I'll have to... I'm not sure what to do other than some sort of delay that would create a race condition.

```
<body>
<span id="ruler"></span>
<div class="container">
  <div class="fg-1" id="name">
    <script> setName () ; </script>
  </div>
  <div class="fg-2" id="title"> 
    <script> setTitle () ; </script>
  </div>
  <div class="bg" id="bg"></div>
</div>
</body>
</html>
```
Which I would think would postpone execution until after any potential CSS is injected.

**Comment by RytoEX** [comment]
`OnLoadEnd` is called when the browser is done loading a frame.  That includes all images and resources.  It's at that point that we inject the custom CSS.  This is not the same as the DOM being loaded/ready, but is akin to the window.onload property for the window.load event.

JavaScript is run as soon as it is encountered by the browser unless you defer it by tying it to some event, such as a ready or load event.

This means that your JavaScript will always be run before OBS injects the CSS, unless you delay its execution.  If you know the CSS properties will always be specified somewhere (you should, you're injecting them), you can defer them with window.onload and then retry your JavaScript every few seconds until it succeeds.  I've tested as much and it seems to work fine.  Since you have full control of the file anyway, it would be easier if you just put the CSS in question into the file to prevent this sort of issue.

This is beginning to seem more like a support question rather than a bug report.  For these kinds of implementation questions, our forums or Discord might be more appropriate.

**Comment by wfolta** [comment]
Thanks for your help! I think I clearly understand now.

But I do think this thread has become, at a minimum, a feature request. (Which you might or might not accept. If not, you can feel free to close it.) 

> This means that your JavaScript will always be run before OBS injects the CSS, unless you delay its execution. If you know the CSS properties will always be specified somewhere (you should, you're injecting them), you can defer them with window.onload and then retry your JavaScript every few seconds until it succeeds. I've tested as much and it seems to work fine. Since you have full control of the file anyway, it would be easier if you just put the CSS in question into the file to prevent this sort of issue.

I'm trying to parameterize my HTML so that the words to be animated could be created in OBS rather than by duplicating the HTML file repeatedly and editing a line or two. I could create a Dock and use broadcasting to communicate to the Browser Source, I guess, but since CSS supports variables it would seem to make a lot of sense to try to use them.

Your Javascript-delay solution still seems like it would create a race situation where the JavaScript is delayed until after OBS CSS injection, but must then get its variables and modify the text contents before the CSS animation reveals the words onscreen. So "every few seconds" would have to be more like milliseconds. Or there would have to be a several second delay before the CSS animation begins to ensure that the JavaScript has time to do its job.

Not criticizing your suggestions, they'd both basically work. But if the OBS CSS injection could occur earlier in the process so that JavaScript within the `<body>` could obtain the CSS variables, it would make it considerably easier to have a simple CSS animation that lets you provide things like onscreen text simply from within the Custom CSS.

Thanks again, and I trust your judgement on whether this could be a feature request or not. Please feel free to close the issue if not. I appreciate your time.

**Comment by RytoEX** [comment]
I've consulted another person on this, and we've agreed that because this is a feature request that we'll close it, because we use GitHub Issues for verified bug reports.

If you'd like to suggest loading CSS earlier during the page load process, you may do so here:
https://ideas.obsproject.com/
