### ISSUE TITLE
CEF 3770 is highly outdated

### ISSUE THREAD

**Issue by dragonbane0** [obsproject/obs-browser#288]
Is there a chance we get a version bump to CEF anytime soon for Windows so we can take advantage of the new Audio API that apparently fixes the audio crackling? 

Audio routing through OBS working properly would be a major benefit for our production, so it's unfortunate that this great feature currently can not be used on Windows. Linux and macOS already use newer versions of CEF, is there any roadmap or particular list of blockers preventing the same on Windows?

The current Chromium build used in OBS Studio on Windows is from **June 2019** and very outdated in many regards, as well as lacking a lot of critical security fixes. Some pages even warn you at this point when you open them in OBS.

PS: I had to open this issue report by using this direct link: https://github.com/obsproject/obs-browser/issues/new. Clicking on "New Issue" would just give me the option to go to a OBS help page instead. Not sure if this is a GitHub bug or not.

**Comment by jp9000** [comment]
3770 is not from 2009. It's from 2019.

Anyway, I would love to update CEF, but there's this problem where the new versions of CEF don't support texture sharing on Windows, so the performance just tanks. So the choice is to either use a terrible performance version, or an older version with high performance. Right now we're choosing high performance. Eventually we'll probably just update it anyway, but it's not some easy decision.

**Comment by dragonbane0** [comment]
Understood. That's pretty unfortunate indeed with the trade-offs

**Comment by WizardCM** [comment]
For updates, you can [follow this discussion](https://github.com/obsproject/obs-studio/discussions/3853#discussioncomment-625248).
