### ISSUE TITLE
CSS inconsistencies when dealing with Fonts

### ISSUE THREAD

**Issue by jetrotal** [obsproject/obs-browser#289]
I found some inconsistencies between OBS and Google Chrome, when dealing with the following CSS properties:
 - top, Left, right, left.
 - font-weight.

Page in Google Chrome:
![image](https://user-images.githubusercontent.com/45118493/115141407-69cf9780-a012-11eb-833a-89dc6fadfdb8.png)

Page in OBS's Browser:
![image](https://user-images.githubusercontent.com/45118493/115141474-dcd90e00-a012-11eb-9288-820e2a7fbcdb.png)

The CSS on the "100" text inside the Green Bar:
![image](https://user-images.githubusercontent.com/45118493/115141554-70124380-a013-11eb-814f-a15cc90cebad.png)

The CSS of one of the Green Bottles 
![image](https://user-images.githubusercontent.com/45118493/115141528-37726a00-a013-11eb-8a9a-37019c62139c.png)

The layers of each bottle are all Custom Text Characters stacked over each other:
![image](https://user-images.githubusercontent.com/45118493/115141881-127ef680-a015-11eb-91a8-30cdeba3fbcb.png)

It was kinda weird to break a layout on a different version of Chromium. 
Maybe I put together some bad or unsuportted CSS...

Right now, I'm testing some workaround that respects the way i had to rig this page...

Thanks in advance!

**Comment by WizardCM** [comment]
Do you only see this in browser sources, or also in browser docks?

**Comment by jetrotal** [comment]
I tested only Browser sources.

Looks misplaced in Browser Docks too.

**Comment by RytoEX** [comment]
Could you please retest in the OBS Studio 27.2 beta?  We've upgraded CEF to a newer version, so I'm curious if this would be resolved.

**Comment by jetrotal** [comment]
Yep, looks alright on the beta version:

![image](https://user-images.githubusercontent.com/45118493/149670575-371a8cf1-2691-457e-903d-7813a18af8c5.png)


Thanks!

**Comment by RytoEX** [comment]
That's great to hear!  I'll close this Issue then.
