### ISSUE TITLE
cef onProcessMessageReceived not called 

### ISSUE THREAD

**Issue by simplytestinglol** [obsproject/obs-browser#291]
### Operating System Info

Ubuntu 18.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.0.2

### OBS Studio Log URL

[0427/114753.137564:INFO:browser-app.cpp(264)] 

### Expected Behavior

[0427/114753.137564:INFO:browser-app.cpp(264)] BrowserApp::OnProcessMessageReceived  (browser:0x7f645c0cdd80, message:Visibility)

### Current Behavior

Not called 

> BrowserApp::OnProcessMessageReceived  (browser:0x7f645c0cdd80, message:Visibility)

### Steps to Reproduce

obs_source_ = obs_source_create("browser_source", name.c_str(), nullptr, nullptr);

### Anything else we should know?

I am creating a cpp application using the obs-browser plugin.
The browser source is created but does not show any output rather shows blank output.

The debugging showed that when BrowserSource::CreateBrowser() sends a CefProcessMessage "visibility" message, it was supposed to be received by BrowserApp::onProcessMessageReceived() but it is not received. Is it because my application is non UI application.

**Comment by WizardCM** [comment]
GitHub issues are only for reproducible issues with obs-browser in the context of being used within OBS Studio.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
