### ISSUE TITLE
Linux Browser Source does not support h264.

### ISSUE THREAD

**Issue by enzanki-ars** [obsproject/obs-browser#293]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://obsproject.com/logs/kZiVzmgL-BT0OBgw

### Expected Behavior

Because the Linux build of Chromium is not build with support for h264, embeded browser source items using h264 do not play.  On Ubuntu at least, they have the `chromium-codecs-ffmpeg-extra` due to the licensing problems.  Is it possible to support this in at least a similar fashion on Linux?

### Current Behavior

Playing a video inside a browser source with h264 should allow the video to play like it does on Windows and macOS.

### Steps to Reproduce

1. Create a browser source with an h264 video embeded.
2. The embeded video should not play with an error regarding unsupported codec.

**Comment by tt2468** [comment]
Unfortunately that is simply because the Spotify builds do enable the build flags for proprietary codecs. You either will have to build CEF yourself, or you can DM me on Discord where I can give you an already built version.

**Comment by WizardCM** [comment]
This is, unfortunately, expected behaviour on Linux unless you build CEF yourself with proprietary codecs enabled.

**Comment by enzanki-ars** [comment]
Out of curiosity, given that it works on Windows, is there a reason why Windows is able to support it but not Linux?  Seems weird given that there should be no difference in licensing between the two platform.

In any case, is there a documented set of flags I can enable to build CEF with these extra codecs for a personal build.  I'm more than willing to compile my own version and keep that up to date on my system, but am not seeing any docs on the CEF pages regarding this specifically.  It _seems_ like adding the following to `GN_DEFINES` should be enough, but not 100% sure: `ffmpeg_branding=Chrome proprietary_codecs=1`
