### ISSUE TITLE
Missing files when importing scene collection with mask filters

### ISSUE THREAD

**Issue by eshy** [obsproject/obs-browser#303]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/dvQDAH2MSVGst_30

### Expected Behavior

When a scene collection is imported and asset files are missing, files used for mask filters should show in that list.

### Current Behavior

While other missing files that are used as sources directly in scenes show up in the missing files list, the filter mask files do not. You have to manually go to each filter setting and replace files

### Steps to Reproduce

1. Create a scene
2. Add any source (I added an image source)
3. Add an Image Mask/Blend filter
4. Close OBS
5. Move or  rename the files
6. Open OBS
...

**Comment by WizardCM** [comment]
Closing this as this is the wrong repo and someone else has since reported it in the correct repo https://github.com/obsproject/obs-studio/issues/5182
