### ISSUE TITLE
[BUG] Browser source completely freezes when VaughnLIVE streams buffer

### ISSUE THREAD

**Issue by shadow93** [obsproject/obs-browser#315]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Png1mFSlZIrieD3B

### Expected Behavior

Be able to view a vaughn.live video stream from browser source

### Current Behavior

When it buffers or loads, it will sometimes completely freeze the browser source and "refresh cache of current page" and if ticked, "refresh browser when scene becomes active" is also unresponsive unless "shutdown source when not visible" is checked.

### Steps to Reproduce

1. Add a vaughn.live stream's url as a browser source
2. wait for streamer to go live, or for stream to randomly buffer
3. it will either load properly (if buffering), or completely freeze (if a user goes live, or sometimes when buffering)
4. Browser source will become completely unresponsive.

**Comment by Fenrirthviti** [comment]
This sounds like an issue with VaughnLIVE, and something that should be reported to them.
