### ISSUE TITLE
Brower Source DevTools crashes OBS by right-clicking in OBS Interact window

### ISSUE THREAD

**Issue by AlcaDesign** [obsproject/obs-browser#321]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/BH6gsGU_iZuzyw0u

### OBS Studio Crash Log URL

https://obsproject.com/logs/6Wv4ZSjf-JFdaLks

### Expected Behavior

Right-clicking in the interact view should be sent and handled by the browser source gracefully.

### Current Behavior

Right-clicking in the interact view crashes OBS.

### Steps to Reproduce

1. Set OBS launch option `--remote-debugging-port=9222`
2. Launch OBS
3. Create an empty scene
4. Create a default browser source and OK it
5. Open `localhost:9222` in a browser
6. Select "OBS | Browser Source"
7. In OBS, open the interact view for the browser source
7. Right-click in the interact view

OBS should crash at this point.

### Anything else we should know?

Related to #320

**Comment by WizardCM** [comment]
This is reproducible in cefclient 3770 (75) with `cefclient.exe --off-screen-rendering-enabled --remote-debugging-port=9123`, but not in cefclient 4430 (90) and 4606 (94), and therefore I'll revisit this bug when we update CEF in OBS on Windows.

**Comment by WizardCM** [comment]
Confirmed this issue is fixed when updating CEF in OBS to CEF 4638 (Chromium 95). I will close this issue once we merge #323
