### ISSUE TITLE
Datalist does not work in browser docks

### ISSUE THREAD

**Issue by ratbo99** [obsproject/obs-browser#322]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

*

### Expected Behavior

could use the Website as Custom Dock like in the Browser, but Datalist attribute didn't work in Dock.

### Current Behavior

cant use a website with datalist as a dock 

### Steps to Reproduce

1.i used a node.js server for my overlay...in chrome everything is fine...but not as a dock in obs
2.
3.
...

**Comment by RytoEX** [comment]
Unless we switch from the CEF/Alloy runtime to the Chrome runtime, I do not see a path for us to change this. Given that we currently have no plans to do so, I'm not sure it makes sense to keep this open, so I'm going to close this for now.
