### ISSUE TITLE
Crash on quitting OBS while playing a video through the browser source

### ISSUE THREAD

**Issue by CoDEmanX** [obsproject/obs-browser#34]
On some machines, OBS crashes on shutdown if the browser source is playing a video (so it seems). It does not occur on all machines, for instance, it crashes on my Windows 10 MacBook Air but not on my Windows 10 desktop computer using the same stable release 0.15.4 of OBS Studio. Another user reported a crash like this here: https://obsproject.com/forum/threads/crashes-frequently-on-program-exit.54126/

On the laptop, there's only VS2013 installed, whereas there's also VS2015 on my desktop computer - not sure if it comes with different runtimes that could cause different behavior or if it's caused by something else.

The crashes could be caused by a race condition, but I'm just guessing. Using the Visual Studio debugger and the CEF debug symbols, it points me to different lines of code with different error messages, but they always seem to come from **w32-pthreads.dll**
- 0xC0000005: access violation while reading at position 0xFFFFFFFFFFFFFFFF
  `if (*mutex == NULL)`
-  mx is a NULL pointer (access violation while reading at position 0x000000...)
  `kind = mx->kind;`

Shall I provide full stack traces?

**Comment by WizardCM** [comment]
Closing this as it was reported before the 2.0 obs-browser rewrite. Feel free to open a new issue if this is still a problem.
