### ISSUE TITLE
Browser source doesn't show on scene change

### ISSUE THREAD

**Issue by Corben78** [obsproject/obs-browser#342]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.2.0 Beta 2

### OBS Studio Log URL

https://obsproject.com/logs/GWNAHFe1jwEmMJkH

### Expected Behavior

Browser source keep showing/working on scene change from a scene where that source wasn't present.

### Current Behavior

When having multiple scenes, where one scene has as source another scene, while the other scene contains a browser source, that browser source stops showing when changing to a scene where that scene with the browser source wasn't included.
When switching from the scene containing the browser source to a scene that is having the previous scene included, it keeps working.
Unfortunately there is nothing in the log file that indicates an error.
It seems not to happen, when I configure the browser source to unload when it's not visible.

### Steps to Reproduce

1. create a scene with a browser source
2. create another scene without that browser source
3. create a third scene including a source referencing the first scene (with the browser source, source NOT set to unload when invisible)
4. switch between scenes and observe how it stops being displayed when switching to the 2nd scene (that doesn't reference the browser source scene) and back
5. reloading the browser source (by making it invisible/visible again, or clearing cache) shows the source again

**Comment by WizardCM** [comment]
This isn't the first time this issue has been reported in Beta 2, but I am unable to reproduce this on either Windows or Ubuntu.

Could you try without any third party plugins installed?

**Comment by WizardCM** [comment]
I've now reproduced this on Windows. We have a potential cause, will do more testing tomorrow.

**Comment by Moulaythami** [comment]
Bug still occuring, you have to include the scene where you want the browser source to still be showing, in the scene you'll be switching to.
