### ISSUE TITLE
Linux OBS browser source does not play web page containing embedded mp4 video.

### ISSUE THREAD

**Issue by teklynk** [obsproject/obs-browser#343]
### Operating System Info

Ubuntu 18.04

### Other OS

Linux Mint 19.3

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/H0-pL2TyJPocH_4L

### Expected Behavior

Expected browser source to play the embedded video just as it does inside a web browser.

### Current Behavior

I am trying to get Twitch clips to play inside a web page that is set as a Browser source. The web page loads inside OBS but the video file does not play, it is just empty. I tested this with various video formats. The only ones that work are webm and ogg, however, Twitch clips are in mp4 format. 

### Steps to Reproduce

1.Tested using https://www.twitch.guru/tools/soclip.html as a browser source - FAILED
2.Created a html page that contains javascript to detect if video/mp4 is supported and playable. Returns True in Chrome, Returns False in OBS.
3.Tested inside and outside of OBS.

**Comment by kkartaltepe** [comment]
Proprietary codecs are not supported in the current release of obs for linux. This has already been resolved for the upcoming 27.2 release.

**Comment by arrowgent** [comment]
the older obs-linuxbrowser works for twitch.guru
https://github.com/bazukas/obs-linuxbrowser/releases/tag/0.6.1

i dont use obs 27.1.3, i use 26.0.2 with obs-browser removed...
ymmv.

**Comment by bStyler** [comment]
> Proprietary codecs are not supported in the current release of obs for linux. This has already been resolved for the upcoming 27.2 release.

@kkartaltepe Can you please elaborate on which propriety codecs will be supported in the upcoming 27.2 release?

**Comment by kkartaltepe** [comment]
Those codecs enabled by the flag `proprietary_codecs`, you would need to poke around in chrome to find a more exact list, the most common that users care about being h264.
