### ISSUE TITLE
Uncaught TypeError: window.obsstudio.setCurrentScene is not a function

### ISSUE THREAD

**Issue by Deuchnord** [obsproject/obs-browser#347]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/2yZ1fpEsv5tg44Fl

### Expected Behavior

In a browser source that has the "Advanced" permission, when the JavaScript [`window.obsstudio.setCurrentScene()`](https://github.com/obsproject/obs-browser/blob/master/README.md#change-scene) function is called, it OBS changes the scene to the one given in parameter.

### Current Behavior

Nothing happens in OBS Studio, and the following error appears in the console:

```
Uncaught TypeError: window.obsstudio.setCurrentScene is not a function
```

When calling `console.log(window.obsstudio)` in the console, we can see that there is no such function called `setCurrentScene()`, so this sounds more like a documentation issue.

### Steps to Reproduce

1. Create the following HTML file:
   ```html
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <script type="text/javascript">
          setTimeout(() => {
              window.obsstudio.setCurrentScene('TargetScene');
          }, 3000);
        </script>
    </body>
    </html>
    ```
2. Create a scene with a browser source and load the HTML file in it.
3. Create a second scene and name it 'TargetScene'.
4. Display the first scene. Wait 3 seconds: nothing happens.

**Comment by gxalpha** [comment]
SetCurrentScene is only available with 27.2.
Try using the Beta version of OBS, it should be available there.
