### ISSUE TITLE
Crash while exiting just after switching to a profile with service browser dock(s) visible

### ISSUE THREAD

**Issue by tytan652** [obsproject/obs-browser#353]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3 (harder to trigger), 27.2 RC4 with CEF 87, 95 MediaHandler, 97 and 98

### OBS Studio Log URL

https://cdn.discordapp.com/attachments/925915897368043570/942029869829726278/Valgrind.txt

https://cdn.discordapp.com/attachments/925915897368043570/942029870135922720/GDB.txt

### Expected Behavior

No crash at all.

### Current Behavior

Crash can happen because of `CrashOnFdOwnershipViolation()`.

### Steps to Reproduce

Firstly, you need an OBS with two profile, one "empty" and one with a service integration connected and at least one service browser dock visible.

1. Run OBS under the "empty" profile
2. Switch to the profile with service integration
3. Exit while service browser dock(s) are loading
4. Your OBS has potentially crashed while CEF was shutting down because of a fd ownership violation.

### Anything else we should know?

- I didn't try to make the crash happen with custom browser docks since dock state is global except with profile with service integrations connected.

- GDB alone didn't gave a readable stacktrace but Valgrind did so I put the Valgrind output as a log.

- For CEF 95 MediaHandler I used the one from the Google Drive, hoping to have debug symbols.

- I didn't try to reproduce it on Windows and macOS, I don't have machine under those OSes.

**Comment by Warchamp7** [comment]
I'm doing some tidying up on the repo, please re-open this if it is still an issue as I am not able to reproduce.

**Comment by tytan652** [comment]
Crash because of FD violation still happen.

**Comment by micsthepick** [comment]
to make this issue more searchable: OBS did not shut down properly during your last session. Would you like to start in Safe Mode? (Starting in safe mode and with a fresh scene collection doesn't help, disabling third party plugins doesn't help)

**Comment by RytoEX** [comment]
> to make this issue more searchable: OBS did not shut down properly during your last session. Would you like to start in Safe Mode? (Starting in safe mode and with a fresh scene collection doesn't help, disabling third party plugins doesn't help)

Safe Mode wasn't added until OBS Studio 30, and this Issue predates that version. Safe Mode is a symptom of a crash - any crash - and not a factor related to this Issue.
