### ISSUE TITLE
 obs-browser: Your browser don't support WebGL

### ISSUE THREAD

**Issue by sy3tem** [obsproject/obs-browser#359]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/4e1dkgqU4QLFbHWF

### Expected Behavior

but the edge browser can display it.

### Current Behavior

on cloud server.no gpu.

### Steps to Reproduce

-

**Comment by Fenrirthviti** [comment]
We do not support virtual instances, this is an issue with your environment, not OBS.
