### ISSUE TITLE
JS Bindings in Browser Dock Not work

### ISSUE THREAD

**Issue by shugen002** [obsproject/obs-browser#376]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/IWEEP9Z1X4ansTXc

### Expected Behavior

Just like in a normal Browser Source

### Current Behavior

The Callback looks like didn't called and return nothing. And the event listener didn't trigger.

### Steps to Reproduce

1. Open OBS with arguments: `--remote-debugging-port=9229` to debug browser
2. Setup a Browser Dock
3. enter the example code in readme.md

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by tt2468** [comment]
To answer the question though, the bindings are only available in browser sources, not panels.

**Comment by tt2468** [comment]
> @tt2468 Is there any way, to listen to events (e.g. `obsRecordingStarted`) from a panel containing a browser source?

Browser panels cannot "contain" OBS sources, and are not related to sources in any way, so no.

**Comment by devmount** [comment]
Wow thanks for answering instantly! And sorry, I might have used the wrong wording here. I meant "Custom Browser Docks". 

![image](https://github.com/obsproject/obs-browser/assets/5441654/1db87c1c-f1f6-4575-8954-45faa7dcae82)

I found that event listeners work when adding the browser source to the sources list, but do not work if I add them as custom browser dock...

**Comment by tt2468** [comment]
Browser docks are browser docks. All browser docks do not have access to the custom OBS window objects.
