### ISSUE TITLE
Request: State getters for current js bindings

### ISSUE THREAD

**Issue by SReject** [obsproject/obs-browser#38]
Along with the js bindings that get called when a change occurs, it'd be handy to, arbitrarily, be able to get the current scene's name and BrowserSource visibility state:

``` javascript
window.obsstudio.activeScene()
// as function returns string
// Returns the currently active scene's name.

window.obsstudio.isVisible()
// as function returns boolean
// Returns true if the browser source is visible
```

**Comment by Simran-B** [comment]
Related to this, I wonder if a Scene and Visibility change occur when the browser source initializes. If so, then you can simple store the values on your end and read the current state from there (needs to be updated on further events).

**Comment by WizardCM** [comment]
You can get the current scene's name via `window.obsstudio.getCurrentScene()` and the visibility using `document.visibilityState` (the Page Visibility API).
