### ISSUE TITLE
Browser Source does not support Bluetooth Web API

### ISSUE THREAD

**Issue by ChristopheCVB** [obsproject/obs-browser#380]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FP7jtK1lmHjIT7lfs

### Expected Behavior

Using latest CEF version, support for Bluetooth Web API should work

### Current Behavior

```javascript
navigator.bluetooth.requestDevice({...})
```
produces the following exception in console `DOMException: Web Bluetooth is not supported on this platform. For a list of supported platforms see: https://goo.gl/J6ASzs`

### Steps to Reproduce

1. Add a Browser source to OBS with javascript that requests for a BT Device
2. See that nothing happens

Example URL using Bluetooth Web API: [Heart Rate Monitor](https://heart-rate-monitor.herokuapp.com/monitor?gender=male&age=37)

**Comment by derrod** [comment]
CEF doesn't support this apparently: https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=18792

In general we recommend to not use any APIs that are meant for use with user-interactive browser sessions or that require access to resources outside of the web itself.

**Comment by derrod** [comment]
Closing this as its an upstream issue. If it ever gets supported in CEF that will likely trickle down to OBS.
