### ISSUE TITLE
No Option to set CEF Startup Paramters.

### ISSUE THREAD

**Issue by lemanschik** [obsproject/obs-browser#389]
### Operating System Info

Other

### Other OS

Awesome OS (WInterOP Runtime)

### OBS Studio Version

29.0.0

### OBS Studio Version (Other)

HEAD

### OBS Studio Log URL

log_not_help_full.org

### OBS Studio Crash Log URL

obs_does_not_log_chrome_errors_anyway_this_fixes_that.org

### Expected Behavior

I Expect that i can supply raw startup parameters so called cli flags to the cef instance that gets started to supply additional needed compatibility flags for varius Situations.

What does it fix: 
- i can get crash reports and deactivate functions that can not work.
- i can start chrome apps with advanced permissions. 
- i can better share the Profile Data to add custom extensions 
- The list is endless overall it is not even avoid able to supply a extra fild to set custom startup parameters.

### Current Behavior

No behavior simply look if something works or not.

### Steps to Reproduce

1. Include browser source
2. Playaround with advanced functionality eg: webgl or wasm. 
3. Expect crashes that are not solve able without cli flags also not even debug able without them.
4. Start asking why they even include that if you can not use it streaming a xcomposit window is much more mem efficent and does not even crash most of the time.
...

### Anything else we should know?

Yes i am chromium engineer i know that this will not be successfull without a option to start it without obs and direct cli binary to start the cef integration with debug output. 

or as proposed here add a extra paramter to set custom flags on startup via the obs interface so that log locations can get defined and other startup behavior like system integrations can get configured.

**Comment by lemanschik** [comment]
## Alternativ 
Only support a single startup parameter at last to set a custom --user-data-dir flag and put the chromium cef build version as most exactly as possible into the interface so that some one can start a matching compatible other integration to interact with the profile.

**Comment by WizardCM** [comment]
We directly pass any command line parameters that OBS doesn't recognise directly to CEF. You can test this by launching OBS with `--remote-debugging-port=9123` and then navigating to http://localhost:9123 - on all platforms.
