### ISSUE TITLE
[Linux] Browser plugin keeps OBS 29.x from closing

### ISSUE THREAD

**Issue by cybik** [obsproject/obs-browser#392]
### Operating System Info

Ubuntu 22.10

### Other OS

Technically, using Pop!_OS

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/9tLgxfOM7GVdLTmC

### Expected Behavior

OBS closes fine.

### Current Behavior

Main OBS app closes okay, but `ps faux | grep obs` shows about five `obs-browser-page` processes (or more) hanging around after using `File > Quit` (not minimizing to system tray here)

### Steps to Reproduce

1. Install OBS
2. Open OBS
3. Setup at least 6 different scenes with different pages
4. Close
5. `ps aux | grep -v grep | grep obs`

### Anything else we should know?

My theory is that any browser plugin "instance" except the current scene, might not get the signal to clear out, and the main OBS object [instance / global / whatever] might be waiting on the plugin.

Not sure if this is a plugin issue, or a main app issue.

**Comment by Fenrirthviti** [comment]
Please test again without third-party plugins installed. Browser subprocesses are normal if something is blocking exit of the program.

**Comment by cybik** [comment]
@Fenrirthviti will do. I'll just note here that I know browser subprocesses are normal by themselves - I code in C++ on occasion, I'm acquainted with threading, processes and the such. Them surviving an app close is what I'm reporting on.

(I might just dive into the code myself if I'm bored enough :P)

**Comment by tt2468** [comment]
I can replicate this as a fault of StreamFX blocking shutdown. The subprocesses you see running are just standard CEF stuff and will exit along with OBS at final shutdown.

**Comment by cybik** [comment]
Oh my.

Validated. Closing this one.

**Comment by cybik** [comment]
Linking bug report in that plugin, for the record

https://github.com/Xaymar/obs-StreamFX/issues/1017

**Comment by cybik** [comment]
@Xaymar you wanted a backtrace/stacktrace, I believe?

**Comment by tt2468** [comment]
I found the issue and have relayed the fix to Xaymar, so I think we're all good.
