### ISSUE TITLE
Animated GIFs stop animating upon exiting "Interact" mode

### ISSUE THREAD

**Issue by randolf** [obsproject/obs-browser#398]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27

### OBS Studio Log URL

N/A

### Expected Behavior

When viewing a web page, animated GIFs should be animated.

### Current Behavior

Animated GIFs are only animated when "Interact" mode is active.  As soon as I exit "Interact" mode all GIF animations stop and reset back to the animated GIF's first frame.

### Steps to Reproduce

Right-click on Linux Browser source and select "Interact" to see animated GIFs on a web page being animated.  When not in "Interact" mode, each animated GIFs is frozen in time at the first frame.

**Comment by WizardCM** [comment]
Please provide a session log file, per the template.

**Comment by derrod** [comment]
Also please try an actually supported version. 27 is rather old.

**Comment by WizardCM** [comment]
Could not reproduce on OBS 29.0 on Ubuntu 22.04.

**Comment by derrod** [comment]
Can't even reproduce with the outdated and unmaintained Snap on Ubuntu 22.04 so I'm chalking this up to using an ancient version from *somewhere*.
