### ISSUE TITLE
crypto.subtle not available on Browser source when using local files

### ISSUE THREAD

**Issue by Hamcha** [obsproject/obs-browser#407]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/OEMiQz1D4Hwv0WLO

### Expected Behavior

The `crypto.subtle` object should be available in both hosted and local files (AFAIK Chromium allows it on file:// and localhost)

### Current Behavior

`crypto.subtle` is only available for remote/hosted pages, shows up as `undefined` in local pages

### Steps to Reproduce

1. Create a browser source with a local file
2. Use the debugger to access the console
3. Check the value of `crypto.subtle`

**Comment by gxalpha** [comment]
@Hamcha please check if adding the flag mentioned above (https://github.com/obsproject/obs-browser/issues/407#issuecomment-1526224544) as a launch flag to OBS fixes this problem.

**Comment by Fenrirthviti** [comment]
The flag should resolve this issue, closing.
