### ISSUE TITLE
Shutdown source when not visible is not working in studio mode

### ISSUE THREAD

**Issue by shailander** [obsproject/obs-browser#412]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.2

### OBS Studio Log URL

-

### Expected Behavior

The browser source should not call any api if the source is not visibile or not active.

### Current Behavior

 But it is still making the api call in both the cases,
1. Not Active
2. Not Visible

### Steps to Reproduce

1. Add a browser source which is calling api regulary
2. Hide the browser source and then check the webpage logs
3. The api call are still being made after hiding
...

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/4120

I don't know if 4120 is specific to browser sources only, or if all sources in OBS have this issue.

**Comment by shailander** [comment]
This is working, browser source only shut's down when any other scene is selected. Not when the browser source is not visible or not active
