### ISSUE TITLE
Browser Cache Not Working

### ISSUE THREAD

**Issue by mafula1** [obsproject/obs-browser#426]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

With "Refresh Browser when scene becomes active" enabled, it should refresh the page without clearing the cache in Studio Mode, like it does with Studio Mode disabled.

### Current Behavior

When using the "Refresh Browser when scene becomes active" in studio mode cache is seemingly cleared and all images need to be reloaded. It works as expected with Studio Mode disabled. Both the normal Http Cache as well as using Service Worker Cache fail.

### Steps to Reproduce

1. Create a Browser Source that contains larger images, with "Refresh Browser when scene becomes active" and "Shutdown when scene not visible" enabled.
2. Create another, empty scene
3. Without Studio Mode, the page is refreshed and all images are loaded instantly from cache
4. With Studio Mode, this does not work

### Anything else we should know?

Cache should not be cleared unless intended by the user. The "Refresh" button also seems to clear the cache (regardless of studio mode enabled or disabled). Perhaps an option can be added whether a "Refresh" should also clear the cache, but either way, the behaviour of the options should be consistent with Studio Mode enabled or disabled.

**Comment by WizardCM** [comment]
This is currently intentional. The goal is that when data in refreshed in a browser source, all data should be refreshed.

https://github.com/obsproject/obs-browser/blob/2ba72dbdfed60acd38fa1ac7a52cbc6617ae8fd1/obs-browser-source.cpp#L475

You should be using other methods of reloading data in your page rather than a full page reload.

**Comment by mafula1** [comment]
It seems I can get the desired effect by using the "obsSourceActiveChanged" event.
