### ISSUE TITLE
CSS mix blend mode with transparent browser source doesn't blend into layers below

### ISSUE THREAD

**Issue by jessicah** [obsproject/obs-browser#443]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/0wS9xtqmnp1bBDMV

### Expected Behavior

Expected `mix-blend-mode` of a transparent browser source to affect layers/sources below the browser source. 

How it would look with proper blending (screenshot from Inkscape):
![image](https://github.com/obsproject/obs-browser/assets/274082/fa0ceb9a-1402-424c-9bdd-3200ddab7caa)

### Current Behavior

The `mix-blend-mode` acts as if there is no background from other OBS sources, so has no effect on the final image.

How it currently looks, no blending done:
![image](https://github.com/obsproject/obs-browser/assets/274082/b91c7ecf-4702-4b56-8419-aae23e2e4459)

### Steps to Reproduce

Add a background image, and then browser source on top using an SVG with mix-blend-mode.

Included sample image and SVGs, and basic OBS scene.

![japan001](https://github.com/obsproject/obs-browser/assets/274082/a79b847d-1b42-4162-943a-3f4de8afefed)
![map fragment on background](https://github.com/obsproject/obs-browser/assets/274082/61e25889-bbcc-4bc6-9cea-5ac3b9e4c358)
![map fragment plain](https://github.com/obsproject/obs-browser/assets/274082/41a938fb-e18e-4ca1-9e7b-26fc6b
[SVG_mixblendmode.json](https://github.com/obsproject/obs-browser/files/15256219/SVG_mixblendmode.json)
4e7533)

**Comment by WizardCM** [comment]
The contents of a browser source are isolated. A browser source has no idea what is behind it. It just has a transparent background.

There are no plans to attempt to hack a method for browser sources to know what's behind them.

OBS sources themselves do support some blending modes:

![image](https://github.com/obsproject/obs-browser/assets/941350/03ac0a72-1880-4228-8596-7090466df10c)

And you may be able to achieve the same effect with third party plugins, such as with a shader filter.
