### ISSUE TITLE
[block & solution] thread is blocked because of browser source

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-browser#466]
### Operating System Info

Windows 11

### Other OS

MAC

### OBS Studio Version

30.2.3

### OBS Studio Log URL

none

### Expected Behavior

none

### Current Behavior

none

### Steps to Reproduce

I have reported it on OBS main github 
https://github.com/obsproject/obs-studio/issues/11545

**Comment by Fenrirthviti** [comment]
Please don't submit duplicate reports. If #11545 should be here, just request that it be moved and we can move it.
