### ISSUE TITLE
Javascript code input in BrowserSource properties

### ISSUE THREAD

**Issue by zanghali** [obsproject/obs-browser#56]
Hi,

First of all I would like to thank you guys for your work this plugin is very helpful for me.
I created this issue after having many problems to build cef and obs. The idea I had initially was to add a js input in BrowserSource properties to be able to automatically make some changes to web pages without having to interact.

I saw in the BrowserLoadHandler class that for setting css it was using js so I thought I can change css input to keep pure js input code. But the problem is that I'm not able to build the plugin... Is it possible to have a prototype of the plugin with this change that I can use. Or if there is another better solution it is welcome.

Thanks again for you good work.

**Comment by CoDEmanX** [comment]
Can you share your code? I managed to build cef/obs, although I remember some problems when using the build (took a while to figure out how to build everything correct and someone said there would be default breakpoints that make it look like it crashes but it actually just loads and hits a breakpoint...).

**Comment by WizardCM** [comment]
Closing in favour of #87
