### ISSUE TITLE
Obs browser wan't "loading" in obs-studio

### ISSUE THREAD

**Issue by Zaharkov** [obsproject/obs-browser#68]
Hello!
I'am trying make some changes in obs-studio+obs-browser and got problem:
After succefull build CEF and obs-studio (like described in README) I'am starting obs-studio (obs64.exe) and there is no plugin "BrowserSource"
(I'am set BUILD_BROWSER = true, and it's was in solution and also it's exists in compiled files)
Can't understand what's wrong =\

P.S. when I just load files from here https://github.com/kc5nra/obs-browser/releases in plugin folder - all work's fine

**Comment by Simran-B** [comment]
Did you check the log? If there's an invalid shader for instance, I believe the entire browser source is hidden due to such an error.
