### ISSUE TITLE
Missing JS Function: getVisibilityState

### ISSUE THREAD

**Issue by SReject** [obsproject/obs-browser#73]
Would be nice if there was a function similar to `getCurrentScene` that would return the visibility state.

```js
// register the callback
window.obsstudio.getVisibilityState(function callback(state) {
    // Called after the BrowerSource's visibility state is retrieved
});
```

**Comment by zavitax** [comment]
What's wrong with `document.hidden` and the rest of the Document Visibility API?
https://www.html5rocks.com/en/tutorials/pagevisibility/intro/

**Comment by WizardCM** [comment]
Just tested this myself - document.hidden definitely seems to do the job.
