### ISSUE TITLE
Make FPS field as an expression

### ISSUE THREAD

**Issue by kutu** [obsproject/obs-browser#75]
I want to be able to type `fps` text in FPS field of browser layer, that way fps of this layer will be the same as set in OBS settings

And if its possible, it also would be handy to type something simple like this `fps / 2`, so if OBS fps settings is set to 60, browser layer will render at 30

This days we have more and more browser layers in OBS, and if I need to change FPS of OBS studio, to free some performance, I also want to go through all the browser layers and change FPS field

Thanks.

**Comment by WizardCM** [comment]
I'm closing this Issue as it's less of a bug and more of a feature request - please post feature requests to [the Ideas site](https://ideas.obsproject.com/) if this is still something you'd still like to see.
