### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Lange** [obsproject/obs-browser#76]
Hey there!

As I was working today, I had OBS Studio crash on me, and the fault seems to have been in `libcef.dll`. Figured I'd share the log here just in case -- feel free to close the issue if this isn't particularly helpful.

When the crash happened, I had recently been opening and closing other apps on my PC (including the webserver which was serving the page loaded into obs-browser) to stress test a graphic. The crash didn't seem to happen in immediate response to any specific action though. It occurred a few seconds after I had last sent an input to my PC.

https://gist.github.com/Lange/7366a249a1c7f31241ffb18e8f661b84

**Comment by OsirisNL** [comment]
Can you reproduce this crash? I could give you the libcef pdb file, so that the crashlog will actually contain the functions in the stack trace.

**Comment by Lange** [comment]
It's not a crash I can intentionally reproduce​. Is there a good way for me
to set up my work environment with this PDB such that it could be used with
any unexpected crashed I get? I probably have about one a week.

**Comment by OsirisNL** [comment]
Sorry it took so long, but here are the libcef pdb's (for the one bundled with obs studio), put them in the corresponding obs-plugins\xxbit folder

http://sokar.nl/cef_binary_3.2987.1581.gf8909fe_windows32_release_symbols.zip
http://sokar.nl/cef_binary_3.2987.1581.gf8909fe_windows64_release_symbols.zip

**Comment by Lange** [comment]
Thanks! I've installed these and will report back with any crashes I have.
