### ISSUE TITLE
Property of order about actual source

### ISSUE THREAD

**Issue by dkonopka** [obsproject/obs-browser#92]
It would be nice if we could detect current Browser Source is:

a) not hidden because of another layer-source, it is possbile to "read" actual "z-index".
b) exists inside whole viewport of streaming source
c) dragged/moved/zoomed in-out

**Comment by WizardCM** [comment]
As nobody else has commented, I will mention: I'm not actually sure how possible it would be to provide information about visibility based on layering, let alone where the source is in the stack. The best you could do is get information about where in the _list_ the source is, which tells you nothing about whether it's covered.

I can see the usefulness of b) and that should be relatively easier to do, and in terms of c) there _may_ be basic transform information that could be made accessible to the source.

**Comment by dkonopka** [comment]
@WizardCM Is there any option to push some features requested?

**Comment by Warchamp7** [comment]
a) is not possible, as a source like an Image could be transparent or translucent and not actually hiding the source despite being on top

b) and c) are outside the scope of obs-browser's relatively simple bindings, but could potentially be accomplished via obs-websocket
