### ISSUE TITLE
Interaction has misaligned mouse cursor on OS X

### ISSUE THREAD

**Issue by quentinmit** [obsproject/obs-browser#99]
Using whatever plugin version comes with OBS 20.1.0, when I "Interact" with a browser, the mouse cursor is in the wrong place.

This is most easy to see the problem is by loading text-heavy content. In this screenshot my cursor is actually at the "C" in "CAROL", but the browser thinks it's at the end of the text selection in the word "at" above:
![obs-cursor](https://user-images.githubusercontent.com/115761/34376368-5fbdd764-eab9-11e7-9bf0-95d2225edefc.png)

I suspect this has to do with the fact that I have a retina MBP. Probably one part of the interaction is dealing in retina coordinates and the other is dealing in non-retina coordinates?

**Comment by eliasthompson** [comment]
Same issue here, forces us to capture with Window Capture (which is terrible on Mac) instead of using a browser source.

**Comment by skeletonbow** [comment]
Same problem on Windows when using Crop/Pad filter on a browser source.

**Comment by mgurov** [comment]
Still reproducible with OBS 25.0.8 (64 bit) on a retina MBP. 

Not reproducible same system when the interaction window moved to an external (non-retina) display.
